### ISSUE TITLE
Two buckets test case issue

### ISSUE THREAD

**Issue by sak96** [exercism/rust#1039]
```rust
#[test]
fn with_same_buckets_but_different_goal_then_it_is_possible() {
    assert_eq!(
        solve(6, 15, 9, &Bucket::One),
        Some(BucketStats {
            moves: 10,
            goal_bucket: Bucket::Two,
            other_bucket: 0,
        })
    );
}
```
### why is the solution 10 moves ?

|move no | one (6) | two (15) | explain|
| ------ | ---- | -- | -- |
|0 | 0 | 0 | init|
| 1 | 6 | 0 | give bucket one is filled|
| 2 | 0 | 0 | empty bucket one (this and below one can be interchanged)|
| 3 | 0 | 15 | fill bucket two |
| 4 | 6 | (9) | bucket two moved to bucket one -> goal reached|

### should this not be the answer ??
4 moves
bucket two is the goal bucket
other bucket has 6 lts

Note: I think i have miss understood something. Can you clarify the same.

**Comment by petertseng** [comment]
4 *would* be the answer were it not specified by the https://github.com/exercism/rust/blob/master/exercises/two-bucket/README.md that you are not allowed to

> you are NOT allowed at any point to have the smaller bucket full and the larger bucket empty (aka, the opposite starting point); that would defeat the purpose of comparing both approaches!

It is an unfortunate restriction, but it is there all the same.

**Comment by petertseng** [comment]
4 *would* be the answer were it not specified by the https://github.com/exercism/rust/blob/master/exercises/two-bucket/README.md that you are not allowed to

> That means, when starting with the larger bucket full, you are NOT allowed at any point to have the smaller bucket full and the larger bucket empty (aka, the opposite starting point); that would defeat the purpose of comparing both approaches!

It is an unfortunate restriction, but it is there all the same.

**Comment by sak96** [comment]
ok look like i missied this. thanks

**Comment by petertseng** [comment]
To deal with this problem, perhaps it would behoove the Rust track to use the improvements to this exercise's README that were enacted in https://github.com/exercism/problem-specifications/pull/1834.
