### ISSUE TITLE
Anagram test case greek characters

### ISSUE THREAD

**Issue by AngelOnFira** [exercism/rust#1051]
I might be misunderstanding something, but I don't understand how this test case could pass. The output seems to contain an item that doesn't share characters with the input. It could be that it's some sneaky unicode gotcha, but in that case, wouldn't it at least be worth leaving a more specific comment on it?

https://github.com/exercism/rust/blob/2378e8b93b29ccc1ef7eed5bb40132f2e5c5e7d8/exercises/anagram/tests/anagram.rs#L103-L112

**Comment by coriolinus** [comment]
The letters in the word, and in the outputs, are greek:

- `Αα`: alpha
- `Ββ`: beta
- `Γγ`: gamma

The point of using non-ascii letters like this is to demonstrate these points:

- non-ascii alphabets can have upper and lower case
- `str::to_lowercase` and `str::to_uppercase` handle them appropriately.
- `str::to_ascii_lowercase` and `str::to_ascii_uppercase` do _not_ handle them appropriately.

[Demonstration on the Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=5878c70dcfe8e3d3646a68e5fc2817df).
