### ISSUE TITLE
CI: ensure it works whether primary branch is master or main

### ISSUE THREAD

**Issue by coriolinus** [exercism/rust#1054]
The simplest part:

https://github.com/exercism/rust/blob/60e98fbb3ad72c0d8f19f8bda0ba993e8936768a/.github/workflows/tests.yml#L7

```diff
- - master
+ - ['master', 'main']
```

The hard part: the rest of the CI checks out `master` branch, because several of the scripts run diffs to determine which files have changed. Therefore, the necessary changes:

- update the scripts so they can operate on `master` or `main`
- update `tests.yml` so it can operate on `master` or `main`

One approach might be to capture an environment variable which github sets for the base branch, and use that. However, that won't always work: that variable isn't set during i.e. the weekly runs.

Another approach might be to determine changed files via the github api instead of via direct git comparisons. This might reduce overall complexity.

**Comment by efx** [comment]
It looks like we can fetch the default branch with:
```sh
 curl --silent -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/exercism/rust  | jq '.default_branch'
 ```

**Comment by efx** [comment]
@coriolinus knocked out the bulk of this with `rg` UNIX magic! I believe we can close.

**Comment by coriolinus** [comment]
Technically it's not solved, as I just renamed everything to use `main` instead of `master` instead of actually fixing things to work with either... but yeah, this is irrelevant now.
