### ISSUE TITLE
[Rust] finish implementing string-vs-str 

### ISSUE THREAD

**Issue by efx** [exercism/rust#1057]
Erik reviewed the Exercism specific content for exercism/v3#1095. We'll want to address that feedback to complete the task!

Main review notes:
https://github.com/exercism/v3/pull/3058#pullrequestreview-573361130

I merged exercism/v3#1095 to keep our momentum going. Do message me directly on Slack if you'd prefer leaving it open or another approach.

@gilescope do you feel like taking on these review comments? If not, I can take it as I need to brush up on the exercism metadata 😅

**Comment by gilescope** [comment]
Thanks. Am just about to start a new job tomorrow so I'm going dark for a
little while...
