### ISSUE TITLE
[Rust] Document deferral and other meta decisions

### ISSUE THREAD

**Issue by workingjubilee** [exercism/rust#1070]
Some languages are harder to learn than others.   Arabic, Cantonese, Japanese, Korean, and Mandarin require 2200 hours to learn (over a year!) for an English speaker, according to the estimation of the Foreign Service Institute. Mostly these involve novel (to an English speaker) ways of writing and speaking, and are not "small" either. Rust as a **programming language** faces a similar challenge as while you can write a (very) simple program quickly, slightly complex systems (including many practice exercises on Exercism) reveal that Rust cuts simultaneously very deep into the core of programming and very wide. It supports many kinds of reasoning and has within itself a distinct "register" called `unsafe {}` which obeys different rules. It has a strong type system and it introduces entirely new concepts like affine typing (lifetimes), seen almost nowhere else in programming. It's a lot. Not all of it will be covered anytime soon.

Some concepts will not have a v3 exercise for them because of technical difficulties, but others are simply low on our priority list because they are rarely used facilities, low enough that unless we suddenly sprout a small army that we are not going to get around to them anytime soon and should save until much later. We should still explicitly list deprioritized concepts somewhere so that we know which ones we are deciding that we will not block further progress on or expect to have anytime soon, and that we can check back on later.

The first such item:
1. Procedural macros (unknown technical modifications also required)

In addition, there are other, possibly implicit meta-decisions that should be documented, but have not been obviously surfaced yet to my conscious notice. We should remain alert for them, and this issue can serve as a discussion point for those.

**Comment by senekor** [comment]
This is not relevant anymore as the syllabus is currently deactivated.
