### ISSUE TITLE
Implement new Concept Exercise: turbofish

### ISSUE THREAD

**Issue by coriolinus** [exercism/rust#1072]
This issue describes how to implement the [`turbofish`](https://turbo.fish/) concept exercise for the rust track.

## Goal

Rust offers the `::<_>` operator, popularly known as the turbofish. AFAIK no other language has this operator, which is used for offering hints to the type inferencer where it would otherwise fail.

In v2, we have shoehorned some instruction about this operator into the `reverse-string` exercise, but this comes with a drawback: it implies that people should use the manual operator even when the code is simpler and clearer without it. 

## Things to teach

- existence of turbofish operator
- how to use turbofish operator
- when using turbofish is required 

## Things not to teach

- policy for using turbofish when not required to solve type inference failure
- partial type hints i.e. `collect::<Result<Vec<_>, _>>()`

## Concepts

- turbofish

## Prequisites

- generics

## Implementing

A sketch of an exercise implementation exists [on the playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=c2c4ac229542b13254443da095449f12)

## Help

If you have any questions while implementing the exercise, please post the questions as comments in this issue.

**Comment by senekor** [comment]
After several failed attempts to create a high-quality syllabus, I believe any future attempts will have to do their own design work from scratch.
