### ISSUE TITLE
[ci] [proposal] lint our bin and _test shell scripts

### ISSUE THREAD

**Issue by efx** [exercism/rust#1110]
As a contributor I would like to see uniform indentation for the internal tooling.
I noticed the indentation looks off:
https://github.com/exercism/rust/blob/673eb06815571e747f71c810bcda9edc972a8df1/_test/ensure-stubs-compile.sh#L35-L43

# proposed solution
- use an [editorconfig](https://editorconfig.org/) file
- add a linting check to our CI workflow. That step would lint any versioned `.sh` file in `bin` or `_test`.

What indentation should be used? Tabbed or spaces? I don't really care but would like one used and enforced 😄

**Comment by coriolinus** [comment]
Sounds plausible. IMO linting is way more powerful than editorconfig, but editorconfig is a good nice-to-have. 

My recommendation for style: four spaces. This keeps things consistent with the recommended rust style; it should be familiar to everyone, and convenient for people whose editors ~~are dumb~~ have trouble distinguishing different file types.

Additional proposal: if we're linting the scripts at all, ensure we also lint them with [shellcheck](https://www.shellcheck.net/).

**Comment by efx** [comment]
Noting the error switch we want to have in each script: https://github.com/exercism/rust/pull/1130#discussion_r574142574

**Comment by efx** [comment]
I found [exercism/github-actions ](https://github.com/exercism/github-actions/)which will come in handy:
- shellcheck: https://github.com/exercism/github-actions/blob/main/.github/workflows/shellcheck.yml
