### ISSUE TITLE
[proposal] create a minimal CONTRIBUTING.md

### ISSUE THREAD

**Issue by efx** [exercism/rust#1111]
As a new contributor I would like to understand and respect the maintenance standards for this repository.
I propose we create a `CONTRIBUTING.md` to briefly document what to expect contributing to this repository.

I and @coriolinus are strapped for time so I am on the fence about doing this. I am on the fence because I do not want to drain from our primary goal of high-quality concept exercises for the v3 launch.

So, the first step would be to decide whether we add one.
Then, let's define simple content.

I would appreciate even if this was something like:
> The current active maintainers are [insert our handles or link to the code] 
> Their time is limited and so a proper introduction to maintaining the Rust track is out of scope!
>  But we would appreciate contributions using these basic guidelines.

As an aside, I feel like contributing `concept/` entries is quite well-defined and self-contained. So it may lend to us documenting clearly how to do it. But it is technical writing. Writing about Rust versus writing Rust. In fact, I would argue most of the v3 concept exercise development has been this kind of meta. Encoding teaching Rust in Exercism's format!

**Comment by coriolinus** [comment]
IMO this is a good idea, but fairly low priority. If we do it, it should be more thorough than the 3-line suggestion. I don't think we should complain about limited time there.

**Comment by efx** [comment]
Topics I would like to cover:
- branches policy in the repository
- how we use issues and labels
    - Defering to the outcome of exercism/docs/issues/27
- merging philosophy and process
- how to create a new concept exercise
    - I am finding creating a draft PR with only `exemplar` a great strategy. I'll plan on drafting a simple how to guide at some point.

**Comment by efx** [comment]
Exercism's community process for contributing and maintaining lives [here](https://github.com/exercism/docs/tree/main/contributing).

**Comment by efx** [comment]
#1177 introduced basic contributing guidelines.

#1156 introduced notes for maintainers.

There are other ideas I had here that may be nice to do, but I will close this issue since the core topic has been addressed.
