### ISSUE TITLE
[ci] fix or deprecate verify-difficulty CI step

### ISSUE THREAD

**Issue by efx** [exercism/rust#1131]
Similar to #1129.

I noticed that the verify difficulty script errors but the CI passes:
https://github.com/exercism/rust/runs/1872578899?check_suite_focus=true#step:6:4

You can see this locally by running:
```sh
./_test/verify-exercise-difficulties.sh
jq: error (at rust/config.json:1913): Cannot index array with string "deprecated"
jq: error (at rust/config.json:1913): Cannot index array with string "deprecated"
```
I could make it fail correctly and then fix the script, but since it involves v2 I would rather deprecate it.

What would you prefer @coriolinus?

**Comment by coriolinus** [comment]
AFAIK the difficulty still shows up to users in v3 as trivial/easy/medium/hard, which makes it valuable to retain both the information and the check. That said, I'm not certain that that's true. @ErikSchierboom is difficulty still a thing in v3?

If yes, then we should fix the script and retain it. If no, then we can just remove the script.

**Comment by ErikSchierboom** [comment]
Difficulty will almost certainly still be a thing in v3, so it should be kept.
