### ISSUE TITLE
[ci] [proposal] lint markdown documentation

### ISSUE THREAD

**Issue by efx** [exercism/rust#1132]
I am learning that much of the v3 content lives in markdown files.
I propose we introduce a linting step to our CI to ensure uniformity and all the benefits One True Way brings to authoring text files.

Exercism's track wide docs also specify [style guidelines](https://github.com/exercism/docs/blob/main/contributing/standards/markdown.md).

👍 to vote yes or comment with qualifications, ideas, improvements.

**Comment by coriolinus** [comment]
I love CI-enforced conventions. The style guidelines look like things which can be verified by a combination of markdownlint and asciidoctor, appropriately configured.

**Comment by efx** [comment]
The JavaScript track has a workflow we can adapt:
https://github.com/exercism/javascript/blob/main/.github/workflows/verify-code-formatting.yml
