### ISSUE TITLE
[CI] [proposal] low-efforts to standardize scripting

### ISSUE THREAD

**Issue by efx** [exercism/rust#1141]
I have been enjoying learning more shell by patching things here and there in our `bin/` and `_test/` files.
As an outsider, I can see little things that tell the story of these scripts being written over time by many folks.

I propose we standardize a small set of guidelines.
I appreciate Google's [scripting guidelines](https://google.github.io/styleguide/shellguide.html) but feel we probably don't need that degree of specificity now. 

# wishlist
- underscores or dashes for file names
- whether the filename should include `.sh` or not
- executable bit set
- favor a single shell interpreter
    - I'd vote BASH simply because it gives you a tad more expressiveness and seems more plausible. Actual usage here is split between `sh` and `bash`. And we can standardize `set -e`.

**Comment by coriolinus** [comment]
My votes:

> underscores or dashes

Underscores. Makes things simpler when upgrading a script into a proper language.

> whether the filename should include the extension.

Yes. You can do a fair bit with arbitrary files with the `file` command and a shebang parser, but neither of those are as visible as a filename extension.

> executable bit set

Yes for scripts that are intended to be called directly; no for scripts which simply define utility functions. This is analogous to the `lib.rs` vs `main.rs` distinction. 

> favor a single interpreter

Yes, and agree that bash is a reasonable default. We just have to be careful about what features we use: OSX still distributes bash v3.x by default, despite v5.x being current; this means that the scripts can't depend on certain features like maps.

Also, all shebangs should be of the form `#!/usr/bin/env bash`, not `/bin/bash`: letting `env` pick the version means that OSX users who have manually installed a modern version aren't stuck using the system version.

One more preference: we should enforce use of `shellcheck` via CI.

**Comment by efx** [comment]
> we should enforce use of shellcheck via CI.

💯 !
I'll use #1110 to capture adding shellcheck.
