### ISSUE TITLE
[poker] Clean up extra comma in test case

### ISSUE THREAD

**Issue by coriolinus** [exercism/rust#1144]
https://github.com/exercism/rust/blob/de9851f98222426d717e3dd666bb71e4fbe17d92/exercises/practice/poker/tests/poker.rs#L34

The extra comma is legal there but looks weird to me.

_Originally posted by @coriolinus in https://github.com/exercism/rust/pull/1143#discussion_r577194472_

**Comment by cwhakes** [comment]
Agreed. It was copied from line 19, which has the same comma.
