### ISSUE TITLE
[ci] remove dead code for Travis CI 

### ISSUE THREAD

**Issue by efx** [exercism/rust#1164]
I noticed a workaround for Travis CI:
https://github.com/exercism/rust/blob/9d90a592fd0c679da7ac83daa62fc53f423e15b5/_test/check-exercises.sh#L59-L61

This ticket tracks:
1. removing that workaround since we use GitHub Actions now
2. spot-checking any other travis CI work arounds in internal tooling and removing them too

**Comment by coriolinus** [comment]
Getting rid of Travis things is fine in general, though in this particular case, I think it's better to retain it. Humans who run the scripts manually probably need progress dots as well, if the process is going to run for 10+ minutes with no other output.

**Comment by efx** [comment]
Got it. I'll simply remove the line about Travis CI.
