### ISSUE TITLE
[v2] metadata.yml files still needed?

### ISSUE THREAD

**Issue by efx** [exercism/rust#1166]
I noticed there are some `metadata.yml` files in some practice exercises:
```
$ fd --hidden .yml exercises/
exercises/practice/decimal/.meta/metadata.yml
exercises/practice/doubly-linked-list/.meta/metadata.yml
exercises/practice/fizzy/.meta/metadata.yml
exercises/practice/luhn-from/.meta/metadata.yml
exercises/practice/luhn-trait/.meta/metadata.yml
exercises/practice/macros/.meta/metadata.yml
exercises/practice/xorcism/.meta/metadata.yml
```
Are these still used?

If so I'll close the issue.
If not, I'll PR to merge any appropriate fields into `config.json` and then remove the .yml files. 😄

**Comment by coriolinus** [comment]
Not sure. @ErikSchierboom, are those still in use, or have they been superseded by other config?

**Comment by ErikSchierboom** [comment]
Those files are indeed superseded. They are there for custom practice exercises (see the above list) and the information in them matches the information in `metadata.yml` files for exercises defined in the prob-specs repo. The metadata.yml files can contain three properties:

- `blurb`
- `source`
- `source_url`

We don't use the `blurb` field as far as I know. Is that correct @iHiD?

The `source` and `source_url` fields have a new location: the exercise's `.meta/config.json` file: https://github.com/exercism/docs/blob/main/anatomy/tracks/practice-exercises.md#file-metaconfigjson
