### ISSUE TITLE
[discussion] should we curate a glossary of Rust jargon?

### ISSUE THREAD

**Issue by efx** [exercism/rust#1242]
As I read and write our documentation I have been noticing unique terms.
Some examples:
- builder pattern
- zero-sized types "ZST"

How would you feel about maintaining  a naive dictionary?
Something like.
term | definition
------------ | -------------
builder pattern | https://en.wikipedia.org/wiki/Builder_pattern
ZST | ZST stands for "Zero-Sized Types". The unit type is one example: `()`. [Unit-like structs](https://doc.rust-lang.org/book/ch05-01-defining-structs.html?highlight=unit,struct#unit-like-structs-without-any-fields) are another. The Rust compiler further optimizes your program by compiling these away.
Content in the first column | Content in the second column

I say naive because we are not lexicographers nor do we want to distract from the content of the track. 
But I feel it could be manage a glossary to avoid having to spell out all terms in our `about.md's`. 

## downsides
- defining things is difficult 😄 
- This falls outside of the Exercism track specification
- The community on discourse has one [thread](https://users.rust-lang.org/t/rust-community-lingo-basics/38883)
- The [rust-tropes project](https://github.com/Enet4/rust-tropes) does this. But it does not seem actively maintained or complete.

**Comment by coriolinus** [comment]
My take is that while a dictionary like this could be valuable, building and maintaining such a thing doesn't really fit in with Exercism's mission. If someone were to fork and update `rust-tropes`, I could see us linking to that. However, I'm not inclined to take on that maintenance burden personally.

**Comment by efx** [comment]
Thanks for chiming in. 
I am leaning in this direction.
Closing with the same rationale as #1237. 
It is a nice idea but would drain our energies.

Unix philosophy applied: do one thing well. :)
