### ISSUE TITLE
Simple Linked List - test_into_vector seems reversed to me.

### ISSUE THREAD

**Issue by tbrown92030** [exercism/rust#1255]
Perhaps I'm misreading the intent of implementing Into<Vec<T>> for this (per the comments in lib.rs) but it seems to me that iteration through a SimpleLinkedList would produce a vector in reverse order from what was pushed. However, the test assumes that the vector produced here would match a vector with elements *in order* of their push. So are we to turn the implementation into an O(N^2) performant routine by inserting each item from the linked list at the beginning of the vector just to satisfy the test as is?

This seems wrong, especially if you take the comments in lib.rs at heart because implementing IntoIterator (and then iterating and collecting to a Vec<T>) would certainly not do this.

**Comment by coriolinus** [comment]
It's true that the intent requires a list of values in the order in which they were pushed. This is for feature parity with `Vec<T>`; you get the values in the order in which they were pushed. It's also true that producing a vector by naively popping values from the list would result in the reverse of that order.

Luckily, there are a variety of efficient strategies which can be used to accomplish this. For example, this implementation from the example:

https://github.com/exercism/rust/blob/1c65bfbe702a7aa5cfe6fb7ef779e72b80b8e7e1/exercises/practice/simple-linked-list/.meta/example.rs#L70-L79

If we were to take an iterator-based approach, we could do something like this. (Note that the `yield` keyword is not yet stable, but there are workarounds in crates like [`genawaiter`](https://crates.io/crates/genawaiter).

```rust
/// pesudocode
impl<T> Node<T> {
  pub fn iter(&self) -> impl Iterator<Item = &T> {
    if let Some(next) = self.next {
      for item in next.iter() {
        yield item;
      }
    }
    yield &self.data;
  }
}
```

You're correct that a naive, `O(n**2)` approach is not great here. However, that does not mean that the tests are wrong. It just means that a non-naive solution is required.
