### ISSUE TITLE
two-bucket.rs - some tests expect suboptimal solution

### ISSUE THREAD

**Issue by almondtools** [exercism/rust#1273]
E.g. test_case_2 with:

- Size of Bucket 1 = 3
- Size of Bucket 2 = 5
- Goal = 1
- Start Bucket = Bucket 2

The solution expects 8 moves, 1 liter in Bucket 2 (the goal) and 3 litres in Bucket 1 but following solution is faster

(0,0) -> (0,5) -> (3,5) -> (3,0) -> (0,3) -> (3,3) -> (1,5)

This solution has 6 moves, 1 liter in Bucket 1 (the goal) and 5 litres in Bucket 2.

Maybe this "solution" should be reviewed because there are multiple explanations:
- I may have not read the problem description carefully (and the upper solution is excluded)
- the test cases are correct but the problem description is insufficient
- the problem description is correct but the tests are not

The affected test cases are:

- test_case_2
- test_case_4
- with_same_buckets_but_different_goal_then_it_is_possible

The failure pattern is the same in all three test cases, they need two moves surplus (goal and other bucket are also different).

**Comment by petertseng** [comment]
Although it is true that the problem description forbids the solution above,

> when starting with the larger bucket full, you are NOT allowed at any point to have the smaller bucket full and the larger bucket empty (aka, the opposite starting point)

(Therefore, you cannot have both states `(0, 5)` and (3, 0)` in the same solution), I personally am not passionate about keeping that requirement intact. One could simply not specify the start bucket and simply ask for the minimum number of moves. Possible solutions are to change it for all tracks in https://github.com/exercism/problem-specifications/blob/main/exercises/two-bucket/description.md, change it for only this track, or do nothing. I have not at this time selected which of these options to recommend.

**Comment by almondtools** [comment]
Thanks for pointing me to the critical constraint. So this makes the issue obsolete.
