### ISSUE TITLE
[Pangram] Discrepancy between instructions and test case

### ISSUE THREAD

**Issue by snowfrogdev** [exercism/rust#1280]
The instruction for the Pangram exercise states:
> The alphabet used consists of ASCII letters a to z, inclusive, and is case insensitive. Input will not contain non-ASCII symbols.

Yet, here is the last test case
```rust
#[test]
fn non_ascii_characters_can_be_in_pangrams() {
    let sentence = "Victor jagt zwölf Boxkämpfer quer über den großen Sylter Deich.";
    assert!(is_pangram(&sentence));
}
```

**Comment by coriolinus** [comment]
That's true. It should be rephrased. The intent is to ensure that non-ascii letters, like punctuation, are ignored.
