### ISSUE TITLE
can't unlock exercise

### ISSUE THREAD

**Issue by lnds** [exercism/rust#1303]
I've completed 102 of 103 exercises, I have completed Rust exercises in v2 before, and yesterday started to complete the new ones. 
However can't unlock CSV Builder exercise, is the last one I need to complete track.
https://exercism.org/tracks/rust/exercises/csv-builder

**Comment by sergree** [comment]
Hello! I faced the same problem. Thank you in advance. 👼

![builder](https://i.ibb.co/hHLhWxs/builder.png)

P.S. 3.0 rocks! 🤘

**Comment by iHiD** [comment]
@sergree Did this fix itself for you too? Thanks for the support :)

**Comment by sergree** [comment]
> 
> 
> @sergree Did this fix itself for you too? Thanks for the support :)

@iHiD Yes (i think?), the 103rd exercise is now hidden. Therefore, it shows me: `You’re 100% through the Rust track` and `Total Exercises 102` now. :)

**Comment by iHiD** [comment]
Thanks :)
