### ISSUE TITLE
external crates not supported error

### ISSUE THREAD

**Issue by jerabaul29** [exercism/rust#1307]
I am trying to continue on the rust track after the update to exercism v3 (really nice update :) ).

I am getting the following error for a solution that passes tests (with ```cargo test```) on my machine. Is this expected or a glitch? Any idea how to fix? I think I should be allowed to use an external crate as part of my solution, right?

![Screenshot from 2021-09-02 22-10-24](https://user-images.githubusercontent.com/8382834/131909539-09b236fa-97e2-4648-803d-cfb02658e897.png)

**Comment by coriolinus** [comment]
The good news is that your code is fine. The bad news is that, as stated in the error message, external crates are not supported by the online checker; you're limited to the capabilities of the standard library for online tests.

Is this blocking your progress through the track?

**Comment by sambeckingham** [comment]
Hey, I just ran into this also.  It doesn't block the track, however the UI is a bit muddled - The "Mark as complete" button is in the side menu on the right, as opposed to the usual place when your solution passes.

**Comment by coriolinus** [comment]
Ok. In that case, I'm going to leave this issue open as a reminder, but please do not expect a resolution any time soon. We've tentatively discussed some approaches by which we might potentially solve this issue, but there's been no real work on them yet.

**Comment by jerabaul29** [comment]
A couple small notes (though this starts to diverge, maybe should use another issues):

- the "old" displayed instructions (corresponding to the ```README.md``` obtained when cloning locally) used to be much more detailed than the "new" instructions that are just a few lines (I liked the old instructions better :) ).  See attached. I cannot find as detailed instructions at https://github.com/exercism/rust/tree/main/exercises/practice/reverse-string , but I guess the old instruction used to be a concatenation of several bits of instructions (with the exercise specific part that is quite short in this exercise, the "things to learn" part, and the "generic how to use", right? See attached the instructions I get locally).

[README.md](https://github.com/exercism/rust/files/7103770/README.md)

- the "old" instructions mentioned explicitly that external crates were possible to use, and I think it was a good thing. I understand that the new instructions do not mention it as it is not supported, but being curious: the aim is that we should be able to use crate again, right, or is it intended that authors should write code "from scratch" (sounds tiring).

**Comment by jerabaul29** [comment]
And @coriolinus about your question :) : yes, unfortunately it is limiting the progress through the track, as the exercise is registered as "failing" and as a consequence it is not unlocking further exercises :( .

**Comment by coriolinus** [comment]
You can still use external crates if you do all your testing locally. Doing so and marking the exercise as complete should let you move forward for now.

**Comment by jerabaul29** [comment]
Aaah, ok, thanks for the tips "marking as complete".

**Comment by mathroc** [comment]
maybe exercises that requires using external crates should be tagged as "online editor incompatible" ?

note that the reverse string exercise is possible, it’s only the feature gated test that’s supposed to use an external crate. the Gigasecond one however can’t be solved at all in the online editor. I guess there are other but I did not look further yet

**Comment by gimait** [comment]
Just dropping to mention that this is also an issue for exercises where the `rand` crate is used. 
I saw the error after finishing the "Simple Cipher" exercise, and "Robot Name" and maybe others use it as well.
Maybe the problems including random generation should be removed (in the case of the simple cypher it's only a small function and a couple of unit tests, I'm not sure if it can be removed from the Robot Name problem).

Also, is it a design decision to not support extern crates, or is it a missing feature? I wouldn't mind having a look into it if help is needed 🙂 (although I must say it would be the first time I look into how the tests are run online, so it might take me some time to figure it out).

**Comment by jerabaul29** [comment]
Just my 2 cents, and I am by no ways a distinguished rustacean, only a complete newbie, but is not one selling point of rust the integration between cargo, crates, and the community providing packages? If this indeed is one of the selling point, I think the ability to use external crates really should be added... Also from a teaching / CS point of view, this is a good teaching for learners, don't reinvent the wheel, use well developed and tested packages instead of your little brittle ad hoc solution, etc.

**Comment by coriolinus** [comment]
> is it a design decision to not support extern crates, or is it a missing feature?

It's a design decision. Test runner containers don't have access to the internet at all, in order to mitigate the possibility for abuse. However, that rules out fetching external crates for obvious reasons.

**Comment by jerabaul29** [comment]
Would it be possible to allow connection to some specific IPs - for example, the servers offering crates -, or to include a "static database" of commonly used crates in their most recent version?

**Comment by gimait** [comment]
> It's a design decision. Test runner containers don't have access to the internet at all, in order to mitigate the possibility for abuse.

I thought so, it makes all the sense. Would it make sense to set up the rust containers with a list of common packages that can be useful for some exercises, though? It should be possible to download those packages when building the container and then loading them with the `--offline` flag for cargo, or with a custom build script.

Again, just an idea, I'm not sure whether it's possible or if it makes sense. I can see how it could become a mess to support some packages and not others in the long run, and it might require a lot of work to set up.

**Comment by coriolinus** [comment]
> Would it make sense to set up the rust containers with a list of common packages

This has been discussed, and in general sentiment favors it, but so far nobody has put in the necessary effort to make it happen. The appropriate repository in which the work would happen is https://github.com/exercism/rust-test-runner/. 

An ideal solution has the following properties:

- Push-button regeneration. We'd want to run a script every month or two to re-generate the container with current versions of the packages, and that regeneration should require no human intervention.
- Support for at least the set of crates supported by play.rust-lang.org. Ideally more, but that's a starting point.
- Continues to conform to the required test runner interface.

I don't have the time to do that work myself for the forseeable future. However, if anyone wants to contribute a PR adding that feature to the test runner, I'd be very happy to review it.

**Comment by gorilych** [comment]
[Dot-dsl](https://exercism.org/tracks/rust/exercises/dot-dsl/) uses external crate `maplit` in tests.

It does make sense at least to allow crates which are in tests.

**Comment by dhovart** [comment]
Wouldn't https://crates.io/crates/cargo-local-registry be a good fit for this?
For the regeneration there could be a different entrypoint that runs it so that it resyncs it with crates.io

**Comment by dhovart** [comment]
I'm on it

**Comment by spathon** [comment]
If anyone have this issue it works now including `Cargo.toml` e.g. `exercism submit Cargo.toml src/lib.rs`

**Comment by RobWalt** [comment]
Hey, I just stumbled upon this. The fix works but I can imagine that not everyone will be successful in navigating to this issue. I think it would be nice if the exercise would include a hint at least pointing to this issue.

It would really add value for me as a user since it was really frustrating to try getting obviously better code to work (get it accepted)

**Comment by petertseng** [comment]
The current instructions in https://github.com/exercism/rust/blob/main/exercises/shared/.docs/help.md are:

>  If you are using any external crates, please consider submitting the `Cargo.toml` file. This will make the review process faster and clearer.

So, perhaps that should be changed to something like "If you are using any external crates, you will also need to submit the `Cargo.toml` file for the test runner to be able to run properly." with a test runner it's now a requirement instead of something you should consider.
