### ISSUE TITLE
The Rust "A Short Fibonacci Sequence" needs better tests

### ISSUE THREAD

**Issue by nilvon9wo** [exercism/rust#1309]
Specifically, the test for the fibonacci() function will accept much the same code as the create_buffer() function, as the only test compares the first and second value against the third value, but it is quite possible for these to be equal without being the fibonacci sequence.

Also, this exercise is a bit ambiguous as it is not clear whether they want the developer to generate the sequence or just return it. Just returning it is presently sufficient, but then this leaves "Fibonacci" rather a red herring and hardly seems like a challenge worth bothering with.

**Comment by coriolinus** [comment]
That's not quite right. The relevant test code is here:

https://github.com/exercism/rust/blob/21ecd788bb4e957e345888fdf13b0784e07d2ed6/exercises/concept/short-fibonacci/tests/short-fibonacci.rs#L21-L23

Note the use of the `windows` function. This produces an iterator; the `for` loop tests the condition repeatedly against _every_ three adjacent numbers in the list produced by `fibonacci()`. By definition, a list for which for every three adjacent numbers, the last is the sum of the first two, must be a section of a fibonacci sequence. 

The point of this exercise is to teach using the `vec!` macro to initialize a list. It's true that that's hardly a challenge worth bothering with, but it's a fundamental prerequisite to many other algorithms.
