### ISSUE TITLE
VSCode integration suggestion

### ISSUE THREAD

**Issue by mathroc** [exercism/rust#1310]
VSCode can [run a development environment inside containers](https://code.visualstudio.com/docs/remote/containers). 
[The container(s) configuration](https://code.visualstudio.com/docs/remote/devcontainerjson-reference) can be shared in a public repo so that anyone can easily [clone the repo and start developing](https://code.visualstudio.com/docs/remote/containers#_quick-start-open-a-git-repository-or-github-pr-in-an-isolated-container-volume) in the same environment

It would be nice to provide such a repo for rust-exercism (and probably others language too), with everything pre-configured (in this case that would be rustc/cargo & exercism CLI)

**Comment by qdelettre** [comment]
Have a look here for inspiration:

https://github.com/qdelettre/exercism-rust-track/tree/main/.devcontainer

I use this for my local env dev, not perfect but working.

**Comment by matthri** [comment]
Hi I would love to help. Is this issue being actively worked on or can I start working on this issue?

**Comment by coriolinus** [comment]
I know of no current active work on this issue. Please feel free to start working on this independently, and post a notice here once you have some work in progress if you wish other people not to start working on it simultaneously.

**Comment by senekor** [comment]
This has been dormant for a while, with apparently little interest. I'm personally not too keen on the feature. I think for quick experimentation, there is the online editor. For local development, setting up the environment properly is a learning experience in itself.

More importantly, I'm not sure how this is supposed to work. As far as I know, every exercise must be self contained. There cannot be any files provided outside of the exercise folder (correct me if I'm wrong on this). That means there would have to be a devcontainer per exercise folder?

Anyway, if someone knows a good way to do it and is willing to put in the work, I would be open to merge this, so feel free to reopen the issue.
