### ISSUE TITLE
practice/accumulate: propose to rename to map & generalize starter code

### ISSUE THREAD

**Issue by koushik-ms** [exercism/rust#1313]
The [accumulate](https://exercism.org/tracks/rust/exercises/accumulate) exercise in rust track effectively requires a [map](https://en.wikipedia.org/wiki/Map_(higher-order_function)) function to be implemented. Even the starter code names the function as map. Could the exercise be renamed to map or is it named accumulate to maintain consistency across all language tracks ?

The starter code provides input and output types as Vec<i32>. However, there are tests that use collections of various types. Starting with a generic Vec<T> as input and return type would make it easier for the student to realize this requirement than reading the rust compiler error messages.

I can submit a PR if this would be acceptable.

**Comment by coriolinus** [comment]
> is it named accumulate to maintain consistency across all language tracks

Yes, precisely that. It's defined [here](https://github.com/exercism/problem-specifications/tree/main/exercises/accumulate).

> Starting with a generic Vec as input and return type would make it easier for the student

That's true, but conflicts with the learning objectives. The goals for this exercise involve the student learning how to write a basic generic function, and there's no better way to learn this than to write it for oneself.
