### ISSUE TITLE
Bug in test suite of "Assembly Line"

### ISSUE THREAD

**Issue by wischi-chr** [exercism/rust#1320]
Because of floating point inaccuracies, one of the test fails when the factors are multiplied in a specific order.

Here is the solution that fails:

```rust
pub fn production_rate_per_hour(speed: u8) -> f64 {
    success_rate(speed) * 221.0 * (speed as f64) // <------ factor order of that line matters!
}

fn success_rate(speed: u8) -> f64 {
    match speed {
        0      => 0.0,
        1..=4  => 1.0,
        5..=8  => 0.9,
        9..=10 => 0.77,
        _ => panic!("speed must be between 0..=10, but received {} instead.", speed),
    }
}

pub fn working_items_per_minute(speed: u8) -> u32 {
    (production_rate_per_hour(speed) / 60.0) as u32
}

```

The test-helper `process_rate_per_hour` should probably check for a few epsilons and not smaller than a single epsilon.

**Comment by koushik-ms** [comment]
Given the success-rate is specified to the 2nd decimal place and the rest of the values have lesser precision, I would like to propose the tests round off (or round down) the returned value to the nearest hundredth of unit, notwithstanding the internal precision of the rust datatypes.

I can propose a PR if this approach is acceptable.

**Comment by coriolinus** [comment]
That approach seems fine to me.
