### ISSUE TITLE
Tests pass in online editor, but not when submitted using client

### ISSUE THREAD

**Issue by drguildo** [exercism/rust#1329]
After solving the Armstrong Numbers exercise with all tests passing, I submitted my code using the command-line client which Failed my solution:

![image](https://user-images.githubusercontent.com/9282/133827173-1144e7ed-c9d4-4b03-8476-f0ea0e56e92b.png)

However, when I click "Continue in editor" and "Run Tests" without touching my code, I'm told that all tests have passed:

![image](https://user-images.githubusercontent.com/9282/133827342-d97f2a0d-740b-4b9d-8f0e-24e2c2e86f57.png)

Here's my code:

```rust
pub fn is_armstrong_number(num: u32) -> bool {
    let digits: Vec<u32> = num
        .to_string()
        .chars()
        .filter_map(|x| x.to_digit(10))
        .map(|x| (x as u32))
        .collect();
    let num_digits = digits.len() as u32;
    let total: u32 = digits.iter().map(|n| n.pow(num_digits)).sum();

    total == num
}
```

**Comment by coriolinus** [comment]
This wasn't your code. As the first error message stated, it was an infrastructure issue.
