### ISSUE TITLE
crate availability should be documented in some way on the site

### ISSUE THREAD

**Issue by zesty** [exercism/rust#1365]
wish list of included documentation:
- the fact that they exist
- a listing of or pointer to a list of the crates that are live and/or available
- a way to find out what versions are latest and which are available
- no need for `extern crate` like many top solutions have
- the need to upload Cargo.toml (not Cargo.lock, contrary to the error message) and the solution file at the same time

example 5d ago iteration, where they seemed to give up on using the rand crate, which was available at the time:
https://exercism.org/tracks/rust/exercises/diffie-hellman/solutions/p1way

example 6d ago iteration, where user got a failure, then uploaded Cargo.lock (likely per the error message), then also got a failure when including Cargo.toml with Cargo.lock, and then seemed to give up --- I suspect (but am too lazy to check) that including Cargo.lock caused the failure:
https://exercism.org/tracks/rust/exercises/diffie-hellman/solutions/viet-nv

**Comment by senekor** [comment]
This is important. Problems with dependencies are pretty pervasive. https://github.com/exercism/rust-test-runner/pull/77 should alleviate many of these problems, as the most recent versions should regularly be made available. Once that's merged, we can also include a pointer to that `Cargo.toml` in the documentation, it includes the exact versions of currently available crates.
