### ISSUE TITLE
Readd prereqs removed in #1378

### ISSUE THREAD

**Issue by iHiD** [exercism/rust#1379]
The following prereqs were removed to make the track pass CI. They need readding once the relevant exercises have been added.

- [ ] magazine-cutout / hashmaps
- [ ] health-statistics / strings
- [ ] rpn-calculator  / mutability
- [ ] rpn-calculator  / loops
- [ ] rpn-calculator / match-basics

**Comment by senekor** [comment]
I think this issue is not relevant anymore, as the syllabus was deactivated and any future work on it will likely start from scratch with the design.
