### ISSUE TITLE
Remarks by Rust analyzer do not show (and do not seem to update after submitting newer iterations)

### ISSUE THREAD

**Issue by broersma** [exercism/rust#1385]
I just finished the Clock exercise, and it seems Exercism's automatic Rust analyzer has some feedback comments.

However, when clicking through to the iteration I see no comments, but this instead (note the robot icon with the "3" next to it, and the empty space below "Our Rust analyzer (...) useful for you:"):

![image](https://user-images.githubusercontent.com/6991518/139426514-bdbdeded-d648-4486-9e14-d6e1a1660f6a.png)

It seems it shows 3 empty `div`s instead of the expected comments.

Furthermore, I found the [source code for the analyzer for Clock](https://github.com/exercism/rust-analyzer/blob/main/src/analyzers/clock.rs), and I deduced which 3 comments I probably got. I fixed these in a newer iteration, and now it seems I should only be getting the 2 compliment comments (regarding `Display for Clock` and `rem_euclid`), however, the interface is still showing there are 3 comments for my last iteration.

I might be mistaking regarding this last point, but I can't be sure unless the contents of the actual comments are shown.

**Comment by anall** [comment]
I opened an issue for this as well at exercism/rust-analyzer#36

**Comment by broersma** [comment]
Fixed by exercism/rust-analyzer#36
