### ISSUE TITLE
The React exercice does not build

### ISSUE THREAD

**Issue by younes-io** [exercism/rust#1387]
I could not compile this [exercice](https://github.com/exercism/rust/tree/main/exercises/practice/react) 

![image](https://user-images.githubusercontent.com/3153107/139559415-4885c8b7-f10d-40ee-8d59-811f82cc55f0.png)

Why?

**Comment by coriolinus** [comment]
Not sure, but I can't replicate it locally. Note that `rustup` does not have the same version as `rustc`. Try running on a stable compiler?

**Comment by younes-io** [comment]
This is very weird:

![image](https://user-images.githubusercontent.com/3153107/139582717-8f7717dc-2077-4246-8310-7917fb5b9445.png)

**Comment by coriolinus** [comment]
Yeah, looks like you've got a nightly toolchain set up for some reason, possibly an override. Here's the [docs](https://rust-lang.github.io/rustup/overrides.html#directory-overrides). Try forcing it to stable and see if it works.

**Comment by halvko** [comment]
@younes-io is this issue solved?

**Comment by younes-io** [comment]
Yes, this can be closed
