### ISSUE TITLE
Timeouts on Resistor Color exercise

### ISSUE THREAD

**Issue by still-flow** [exercism/rust#1411]
Some people appear to be experiencing sporadic timeouts on tests for this exercise. Their code appears to be fine locally.

Is that a test-runner issue?

**Comment by coriolinus** [comment]
Yes, that's a test runner issue. I believe that there's a max duration hard-coded into the test runner; it may be worth exploring whether it's possible to increase that duration for this exercise at least.

**Comment by still-flow** [comment]
I see. It must be related to exercism/rust-test-runner#30 then. But I can't seem to find the timeout feature anywhere in the code -- so is that somewhere deeper in the infrastructure?

**Comment by PieterVanZyl-Dev** [comment]
It's likely related to the fact that this specific exercise has external crates.

It's slower than all the other exercises locally and on the test runner.
a quick solution might be to have a cached crate ?

**Comment by yukeevrana** [comment]
I still have same problem. I was advised to leave a comment in the issue if there is one. So here I am. Кeady to provide information about my solution, if necessary.

**Comment by rHermes** [comment]
I had the same issue, worked on the 4th try

**Comment by gabeio** [comment]
The dependencies on this exercise were fairly large (~87MB). Depending on network speed, crates.io speed (I average ~20s) and then a non-cached build+test takes ~9s on a local, which I'm guessing is more powerful than the runner. It probably is just luck of the draw on who's will not timeout, or have to run back to back to try and try to hit a build runner who already downloaded the deps. I had timeouts on multiple ~6 tries before I got it to work.

**Comment by hrunting** [comment]
This still appears to be an issue. Any progress on this? I cannot submit results either locally or through the web editor. On my local machine, it takes less than 10 seconds.

**Comment by lucroch** [comment]
Having the same issue with this one.
It does in fact work sometime, out of sheer luck I believe. The timeout duration might be really close to the average duration of the test.
Just curious, isn't there a way to simply manually increase the timeout to this exercise?

**Comment by senekor** [comment]
The test runner was [deactivated](https://github.com/exercism/rust/commit/faf6122145505e2f44b4f8ad3c18ac9e77953264) for this exact reason. Currently, the learning mode (including this concept exercise) is disabled anyway.

Related: Solving https://github.com/exercism/rust-test-runner/issues/35 could improve build times of exercise solutions with external crates significantly.
