### ISSUE TITLE
Incorrect test assertion in Rust / Lucian's Luscious Lasagna

### ISSUE THREAD

**Issue by untaggable** [exercism/rust#1415]
Issue: wrong wrong assertion for `elapsed_time_in_minutes` function

Link: https://exercism.org/tracks/rust/exercises/lucians-luscious-lasagna

It does say that the result of `elapsed_time_in_minutes(1, 30)` is: `number of layers * 2 + 40 - actual minutes in oven`

Failed 2 tests:

1) elapsed_time_in_minutes(1, 30) should return `1 * 2 + 40 - 30 = 12` but assertions wants 32 `assert_eq!(32, elapsed_time_in_minutes(1, 30));`
2) elapsed_time_in_minutes(4, 8) should return `4 * 2 + 40 - 8 = 40` but assertions wants 16 `assert_eq!(40, elapsed_time_in_minutes(4, 8));`

**Comment by coriolinus** [comment]
I haven't yet looked too deeply into this, but I'd point out that the `main` branch includes an [example implementation](https://github.com/exercism/rust/blob/main/exercises/concept/lucians-luscious-lasagna/.meta/exemplar.rs) which [passes the existing tests on CI](https://github.com/exercism/rust/runs/4460146093?check_suite_focus=true). Your PR changing the tests [causes the example to fail](https://github.com/exercism/rust/runs/4591745743?check_suite_focus=true). This means that one of three possibilities will happen:

- There is a discrepancy between the problem text and the test cases, and a PR changes both the test cases and the example solution.
- There is a discrepancy between the problem text and the test cases, and a PR changes the problem text.
- There is no discrepancy between the problem text and the test cases, so we close this issue and #1416.

**Comment by untaggable** [comment]
@coriolinus yeah, probably I misunderstood the text. 
So I'll close the issue and PR for now.
