### ISSUE TITLE
Allegies typos

### ISSUE THREAD

**Issue by natehouk** [exercism/rust#1452]
There are two typos in the Allergies explanation:

"An important concept in low level programming is [bitfiled](https://en.wikipedia.org/wiki/Bit_field)."

It should be spelled "programming and also "Bit field"

However, I don't see the explanation as part of the code for the Allergies exercise, so I am not sure how to make a PR to fix?

**Comment by coriolinus** [comment]
Please screenshot where you see the typo; I cannot find that typo in the
`exercism/rust` repo.

**Comment by natehouk** [comment]
Oops, I got confused where I saw this. It was elsewhere, not in the exercise itself. I will close this.
