### ISSUE TITLE
xorcism test issue for statefulness test

### ISSUE THREAD

**Issue by Yong-Zhao** [exercism/rust#1457]
https://github.com/exercism/rust/blob/8dd993e78be0132fcb36d69ebf11b5742f3c2404/exercises/practice/xorcism/tests/xorcism.rs#L66

That makes the type of the key be &[i32; 8].  Shouldn't the line be changed so that the type of the key is &[u8; 8]?
    let key = &[0_u8, 1, 2, 3, 4, 5, 6, 7];

**Comment by coriolinus** [comment]
Given a little more context, we see that `key` is immediately (and only) used in `Xorcism::new`. 

https://github.com/exercism/rust/blob/8dd993e78be0132fcb36d69ebf11b5742f3c2404/exercises/practice/xorcism/tests/xorcism.rs#L66-L69

We can look at the signature of `Xorcism::new` for a little more detail.

https://github.com/exercism/rust/blob/8dd993e78be0132fcb36d69ebf11b5742f3c2404/exercises/practice/xorcism/src/lib.rs#L10-L13

While this obviously depends on the particular trait bounds that students write, the intent is that those bounds look something like 

https://github.com/exercism/rust/blob/8dd993e78be0132fcb36d69ebf11b5742f3c2404/exercises/practice/xorcism/.meta/example.rs#L34-L36

Given bounds like that, rustc is smart enough to figure out that the type system resolves if `key`'s is `&[u8]` but not if it is `&[i32]`; it therefore infers that we intended it to be `&[u8]`. We don't need explicit type markers, given good enough trait bounds.
