### ISSUE TITLE
Lucian's Luscious Lasagna: misspelling

### ISSUE THREAD

**Issue by degradka** [exercism/rust#1461]
This stub file contains items **which** aren't used yet;

more right would be putting "that" instead of which

**Comment by iHiD** [comment]
The rule is that "which" should always have a comma in front of it; the clause before it should be able to stand alone, and the clause after which should be a clarifying or additional phrase (a "non-defining clause").

So either of these would be correct:
> Depending on your implementation, there are a variety of potential errors that might occur.
> Depending on your implementation, there are a variety of potential errors, which might occur.

But the second doesn't feel natural as the "which might occur" is a key part of what we're saying here, not an addition. So it should be the first option.

It's one of those things that's really minor in a situation like this, but I had it beaten into me enough at school that it does jump out for me when I read things too, so I totally get why @degradka flagged it! 🙂 

---

Sample Source: https://www.grammarly.com/blog/which-vs-that/?gclid=CjwKCAiAyPyQBhB6EiwAFUuakpBtX8oT7pTyewMcjJZAu9G9sSzOJ8jTIoZ6HdkXxR8H7qotLbiH6hoC710QAvD_BwE&gclsrc=aw.ds

**Comment by degradka** [comment]
The co-founder of Exercism himself 👀
Appreciate your answer, hope it will be fixed :yellow_heart:

**Comment by iHiD** [comment]
@degradka The easiest way to fix it is to clone the repo, update the copy and submit a Pull Request. Then you can get some Exercism Reputation for it too! 🙂

**Comment by degradka** [comment]
Oh, I see. Thank you ☺️

**Comment by degradka** [comment]
@iHiD Done.
