### ISSUE TITLE
Debugging instructions are missing

### ISSUE THREAD

**Issue by vitalyPru** [exercism/rust#1464]
Please, consider the possibility to allow debug print during Rst tests.

**Comment by iHiD** [comment]
:+1: Reopened and transfering to Rust repo.

**Comment by coriolinus** [comment]
Either of the `dbg!` or `eprintln!` macros will emit to standard error, which _may_ be captured as debug output; I'd need to double-check the test runner to see what precisely gets captured. If it is in fact captured, then the blurb should mention (and link to documentation for) each of those.

**Comment by ErikSchierboom** [comment]
Here are the docs for the file that should contain the debug instructions (provided it does indeed work): https://exercism.org/docs/building/tracks/shared-files#h-file-debug-md

**Comment by coriolinus** [comment]
It appears that the test runner sends the debug output to a file called `results.out`, which I believe to have been meaningful in an older version of the test runner interface. 

https://github.com/exercism/rust-test-runner/blob/2e5c4cb7398aa431ccf3bb3cbc4b17fa82e1a41b/bin/run.sh#L41

Until that is updated into the current interface, I suspect that the output simply isn't being captured.

**Comment by senekor** [comment]
Until recently, both `stdout` and `stderr` were captured by the test runner, but they were displayed together as one big string with the error from the failed assertion of the test.

I recently updated the test runner to separate these two, for slightly improved UX. Here's my manual test:

![image](https://github.com/exercism/rust/assets/54984957/237197e7-1fca-42c5-9ed4-091bc6cbde44)

I will update the documentation accordingly.
