### ISSUE TITLE
magazine-cutout: It's possible to solve at caracter level not words with actual test

### ISSUE THREAD

**Issue by darnuria** [exercism/rust#1465]
Hello,

With the actual [test-set](https://github.com/exercism/rust/blob/main/exercises/concept/magazine-cutout/tests/magazine-cutout.rs) it's possible to write a solution that match if a letter in `magazine` exist: increment the map, then decrement by letters encountered in the `note`.

It's that voluntary? If no I can add some test.

It allow:

- magazine: `strawberry cat`
- note: `stray cat`

By reading the exercise it's not intended because we examine at words cuts-outs.

If new test are needed I can try to write some to run out this case.

**Comment by coriolinus** [comment]
That's fine. The affordances of the exercise encourage solving it at the word level, but solving it at the character level doesn't cause any problems for either the learning objective or for the lesson narrative. I don't think this is a problem that needs solving. 

Thanks for bringing up the issue!
