### ISSUE TITLE
Implement new Concept Exercise: traits (Issue WIP)

### ISSUE THREAD

**Issue by nahuakang** [exercism/rust#1482]
Per [discussion](https://github.com/exercism/rust/issues/1065), there should be a concept exercise for `traits` after implementing the concept exercise for `iterators`.

## Getting started

WIP

## Learning objectives

Student should be able to:

- implement a standard library trait (could be `Iterator`)
- write a trait and implement it on some types
- implement a generic function bounded on their custom trait

## Out of scope

WIP

## Concepts

loops
ranges
patterns

## Prerequisites

Prerequisites might be `iterators` and `generics` (if we use the third suggested learning objective).

### Hints

WIP

### After

WIP

## Analyzer

WIP

## Implementing

WIP

## Help

If you have any questions while implementing the exercise, please post the questions as comments in this issue.

**Comment by coriolinus** [comment]
Some possible learning objectives:

- implement a standard library trait (suggest `Iterator`)
- write a trait and implement it on some types
- implement a generic function bounded on their custom trait

Prerequisites might be `iterators` and `generics` (if we use the third suggested learning objective)

**Comment by senekor** [comment]
After several failed attempts to create a high-quality syllabus, I believe any future attempts will have to do their own design work from scratch.
