### ISSUE TITLE
Resistor Color using obsolete crate version

### ISSUE THREAD

**Issue by amab8901** [exercism/rust#1495]
Resistor Color relies on version 0.7.0 of crate `enum-iterator`. Latest version is 1.0.0. The vast majority of community solutions for this exercise require the import of `IntoEnumIterator` from `enum-iterator`, but it's available only in version 0.7.0 and not in 1.0.0. I think you should update the exercise to be based on the latest version instead of relying on obsolete legacy

**Comment by coriolinus** [comment]
Agreed, PRs welcome.
