### ISSUE TITLE
Affine Cipher problem description is incomplete

### ISSUE THREAD

**Issue by asarkar** [exercism/rust#1496]
The problem statement states m=26, but the tests use upper and lowercase letter, whitespace, punctuations, and numbers. Last I checked, all those didn't fit in the lower case ASCII alphabet range of a..z.

**Comment by coriolinus** [comment]
From the instructions:

> Ciphertext is written out in groups of fixed length, the traditional group size being 5 letters, and punctuation is excluded.

It is true that the instructions do not mention that digits should be passed through unchanged.

**Comment by coriolinus** [comment]
White space and punctuation are stripped out. Otherwise, yes.

**Comment by AryanGodara** [comment]
Can I open a PR to work on this Issue?
I am relatively new to Rust, but I have good experience in open-source, and want to contribute to exercism.

**Comment by coriolinus** [comment]
Yes the team always appreciates pull requests.

**Comment by senekor** [comment]
I synced this exercise with problem-specifications a couple months ago and the instructions now include the following:

> For the purpose of this exercise, digits are valid input but they are not encrypted.
> Spaces and punctuation characters are excluded.

If this can / shoud still be improved, it would be best to take the discussion to the problem-specifications repository.
