### ISSUE TITLE
Project Euler is not meant for learning a programming language

### ISSUE THREAD

**Issue by asarkar** [exercism/rust#1497]
Picking up exercises from Project Euler may be tempting, but it is a waste of time for the students looking to learn a programming language. We enrolled in a Rust track, not a middle school math track for bonus points. What can exercises like [Difference Of Squares](https://exercism.org/tracks/rust/exercises/difference-of-squares) and [Palindrome Products](https://exercism.org/tracks/rust/exercises/palindrome-products) possibly teach about Rust?
Questions like these are a prime reason there should be a feedback option for students.

**Comment by coriolinus** [comment]
These are both practice exercises. The intent is to learn Rust by writing code: not necessarily focused code aimed at teaching a particular concept, just code at all. The premise, which I wholeheartedly agree with, is that the most efficient way to learn a language is to write a bunch of code in that language. If you don't like those exercises, don't do them.

If you want to improve the exercises or contribute new ones, please feel free to open PRs in this repo. If you want to advocate for new features such as student feedback options, feel free to open an issue in exercism/exercism. If you are proposing to simply remove all exercises from this track which originate from Project Euler, then I reject that proposal with prejudice.

**Comment by iHiD** [comment]
> What can exercises like [Difference Of Squares](https://exercism.org/tracks/rust/exercises/difference-of-squares) possibly teach?

For anyone else that ever comes back to this, I just took a look at 4 sample solutions and learnt quite a lot about Rust in the 30secs it took to read them all:
- https://exercism.org/tracks/rust/exercises/difference-of-squares/solutions/MathiasLengler
- https://exercism.org/tracks/rust/exercises/difference-of-squares/solutions/joseph-fourier
- https://exercism.org/tracks/rust/exercises/difference-of-squares/solutions/hayatoito
- https://exercism.org/tracks/rust/exercises/difference-of-squares/solutions/smokey42
