### ISSUE TITLE
Test runner ignores Cargo.toml

### ISSUE THREAD

**Issue by asarkar** [exercism/rust#1498]
https://exercism.org/tracks/rust/exercises/sieve/iterations?idx=2

I submitted the first iteration but forgot to include the `Cargo.toml` that had an external dependency. Submitted again, including `Cargo.toml`, but the runner ignores it.

The root cause of this issue is that an exercise directory can be downloaded, but can't be submitted. Cherrypicking individual files is prone to mistake.

**Comment by coriolinus** [comment]
> https://exercism.org/tracks/rust/exercises/sieve/iterations?idx=2

That link points to the exercise as submitted by the logged-in user; I can't see your submission from there, only my own.

>  Submitted again, including Cargo.toml, but the runner ignores it.

Hmm, it's not supposed to ignore it. I'll attempt to replicate later.

> Cherrypicking individual files is prone to mistake.

Agree! There's been some talk in the past about potentially having the CLI package up the important files from the exercise directory, but it ran into the issue that each language track needs to be able to configure the set of important files flexibly, which is apparently hard. For example, in rust, we'd want to auto-submit something like `["Cargo.toml", "build.rs", "src/**/*.rs"]`, but that glob is doing a lot of work. 

Maybe open an issue in exercism/cli and see how people feel about the idea these days.

**Comment by asarkar** [comment]
@coriolinus Here...

Cargo.toml:
```
[package]
edition = "2021"
name = "sieve"
version = "1.1.0"
[dependencies]
priority-queue = "1.2.2"
```
Exercise:
```
use priority_queue::PriorityQueue;

pub fn primes_up_to(upper_bound: u64) -> Vec<u64> {
    let n = upper_bound + 1;
    let sqrt = (n as f64).sqrt() as u64;
    let mut primes = Vec::<u64>::new();
    let mut composites = PriorityQueue::<(u64, u64), i64>::new();
    for i in 2..n {
        if composites.is_empty() || composites.peek().unwrap().0 .0 != i {
            let x = i * i;
            if i <= sqrt {
                composites.push((x, i), -(x as i64));
            }
            primes.push(i);
        } else {
            while !composites.is_empty() && composites.peek().unwrap().0 .0 == i {
                let ((x, y), _) = composites.pop().unwrap();
                if x + y <= n {
                    composites.push((x + y, y), -((x + y) as i64));
                }
            }
        }
    }
    primes
}
```

Error:
```
We received the following error when we ran your code:
WARNING: student did not upload Cargo.lock. This may cause build errors.
error: failed to get `priority-queue` as a dependency of package `sieve v1.1.0 (/mnt/exercism-iteration)`

Caused by:
  failed to query replaced source registry `crates-io`

Caused by:
  failed to read `/opt/test-runner/local-registry/index/pr/io/priority-queue`

Caused by:
  No such file or directory (os error 2)
  ```

**Comment by coriolinus** [comment]
`priority_queue` is not in the list of [crates supported by the test runner](https://github.com/exercism/rust-test-runner/blob/main/local-registry/supported_crates).

**Comment by asarkar** [comment]
Why does the test runner care what crate is used by the code?

**Comment by coriolinus** [comment]
In order to prevent bad behavior (i.e. cryptocurrency mining, DDOS attacks, etc), the test runner doesn't have a connection to the outside internet. Instead, it provides a set of commonly-used crates which are pre-built into the image. The whole setup is heavily inspired by the Rust Playground.

What this means is that if your code requests a crate or a version not already present in the test runner, it can't fetch it.

**Comment by asarkar** [comment]
Can we add the `priority-queue` crate please, it’s clearly not harmful.

**Comment by coriolinus** [comment]
The list is (per [the PR which added it](https://github.com/exercism/rust-test-runner/pull/27)) the top 100 crates off crates.io, not something manually curated, because that would be too much work. 

You don't need an external crate for a priority queue though; [`std::collections::BinaryHeap`](https://doc.rust-lang.org/std/collections/struct.BinaryHeap.html) implements a priority queue also.

**Comment by asarkar** [comment]
`std::collections::BinaryHeap` worked, thank you.
