### ISSUE TITLE
XORCISM on Rust track still broken for me

### ISSUE THREAD

**Issue by jwaddle** [exercism/rust#1501]
I originally raised this issue in #1422 and it was supposedly fixed in #1423, but I still got the following error running tests when I try to submit:

We received the following error when we ran your code:
WARNING: student did not upload Cargo.lock. This may cause build errors.
error: failed to select a version for the requirement `hexlit = "^0.3.0"`
candidate versions found which didn't match: 0.5.3
location searched: `/opt/test-runner/local-registry` index (which is replacing registry `crates-io`)
required by package `xorcism v0.1.0 (/mnt/exercism-iteration)`
perhaps a crate was updated and forgotten to be re-vendored?
As a reminder, you're using offline mode (--offline) which can sometimes cause surprising resolution failures, if this error is too confusing you may wish to retry without the offline flag.

I used the "reset to exercise start" feature in the editor, and now I get this error when running tests:

We received the following error when we ran your code:
WARNING: student did not upload Cargo.lock. This may cause build errors.
error: failed to select a version for the requirement `rstest = "^0.6.4"`
candidate versions found which didn't match: 0.12.0
location searched: `/opt/test-runner/local-registry` index (which is replacing registry `crates-io`)
required by package `xorcism v0.1.0 (/mnt/exercism-iteration)`
perhaps a crate was updated and forgotten to be re-vendored?
As a reminder, you're using offline mode (--offline) which can sometimes cause surprising resolution failures, if this error is too confusing you may wish to retry without the offline flag.

Is my xorcism exercise in a broken state?   Is there a way to truly reset it?  I have a copy of my working code locally.

**Comment by asarkar** [comment]
Your problem could be https://github.com/exercism/rust/issues/1498#issuecomment-1146264377.

**Comment by coriolinus** [comment]
The error includes an appropriate solution. It tells you that the online test runner doesn't have a version of `rstest` available matching `^0.6.4`, but that `0.12.0` is available. Therefore, changing the requirement in `Cargo.toml` should fix this. There is also #1503 which should be a more general fix.
