### ISSUE TITLE
Only 9 iterations visible

### ISSUE THREAD

**Issue by jwaddle** [exercism/rust#1515]
I have been trying to resubmit a Rust solution for XORCISM (changing Cargo.toml) which runs locally but not on the test-runner (see #1422, #1501, #1513), and it has driven the iteration number up to 11.  In the UI, however, it only displays up to iteration 9, which is labelled "latest".   This is preventing me from attempting to fix the issues in #1422, #1501, etc.

<img width="1450" alt="Screen Shot 2022-06-12 at 10 41 07 PM" src="https://user-images.githubusercontent.com/5522478/173270302-67b30d51-6cb2-405f-a72a-1a3e6bba0910.png">

An easy fix would be a way to completely reset an exercise.  This could also possibly help with issues that arose from downloading the exercise long ago, version numbers in Cargo.toml being out of date, etc.

**Comment by jwaddle** [comment]
The newer iterations are visible now, it took them a while to become visible.

**Comment by jwaddle** [comment]
I thought I had closed it as I had "Close with comment" selected when I commented last.  I'm not sure if I can close as the opener, or if the person who closes has to be a collaborator.

I agree the ability to reset problems would be exercism/exercism :).

**Comment by coriolinus** [comment]
You should have permissions to close it as the author, but no problem.
