### ISSUE TITLE
Assembly line test fails

### ISSUE THREAD

**Issue by peregrineshahin** [exercism/rust#1520]
https://exercism.org/tracks/rust/exercises/assembly-line/edit

Hello this is my second exercise in my whole rust journey and it is driving me insane,

can someone explain why my code doesn't work but the one listed in meta folder does?

```
// This stub file contains items that aren't used yet; feel free to remove this module attribute
// to enable stricter warnings.
#![allow(unused)]
const PRODUCTION_RATE_DEFAULT: f64 = 211.;
pub fn production_rate_per_hour(speed: u8) -> f64 {
    let mut successful_rate: f64 = 0.0;
       match speed {
        0 =>  successful_rate = 0.0,
        1..=4 => successful_rate = 1.0, 
        5..=8 => successful_rate = 0.9, 
        9..=10 => successful_rate = 0.77, 
        _ => panic!("Speed should be a value from 0 to 10"),
    }
    return PRODUCTION_RATE_DEFAULT * speed as f64 * successful_rate
}
pub fn working_items_per_minute(speed: u8) -> u32 {
    (production_rate_per_hour(speed) / 60.0) as u32
}
```

solution from code in this repo:

```
const PRODUCTION_RATE_DEFAULT: f64 = 221.;

pub fn production_rate_per_hour(speed: u8) -> f64 {
    match speed {
        0 => 0.0,
        s @ 1..=4 => PRODUCTION_RATE_DEFAULT * s as f64,
        s @ 5..=8 => PRODUCTION_RATE_DEFAULT * s as f64 * 0.9,
        s @ 9..=10 => PRODUCTION_RATE_DEFAULT * s as f64 * 0.77,
        _ => panic!("Speed should be a value from 0 to 10"),
    }
}

pub fn working_items_per_minute(speed: u8) -> u32 {
    (production_rate_per_hour(speed) / 60.0) as u32
}

```

https://github.com/exercism/rust/blob/main/exercises/concept/assembly-line/.meta/exemplar.rs

![CaptureRust](https://user-images.githubusercontent.com/41402573/176163992-de87ae60-fa3c-4837-a8c0-dd45a4feb333.PNG)

![CaptureRust 3](https://user-images.githubusercontent.com/41402573/176164995-686e44f2-3a46-4096-9bac-7e108a39ac40.PNG)

meanwhile, I tried rounding, trunc-ing, and flooring nothing worked!

I know I'm not supposed to use a mutable variable but how is it prints a difference of one =>
'production_rate_per_minute_at_speed_ten' panicked at 'assertion failed: (left == right)
  left: 27,
 right: 28
 
 thanks

**Comment by coriolinus** [comment]
Look at the value of `PRODUCTION_RATE_DEFAULT` in both samples.

Next time, please ask a mentor instead of posting an issue here.
