### ISSUE TITLE
lucians-luscious-lasagna: Tests pass despite function never returning

### ISSUE THREAD

**Issue by roxgib** [exercism/rust#1536]
I'm mentoring a student who submitted this code for the lasagna exercise:

```
pub fn remaining_minutes_in_oven(actual_minutes_in_oven: i32) -> i32 {
    let oven_time = 40;
    let minutes_left_in_oven = expected_minutes_in_oven() - actual_minutes_in_oven;
     while actual_minutes_in_oven <= oven_time {
         println!("The remaining minutes in the oven is: {} ", minutes_left_in_oven);
     }
    return minutes_left_in_oven
}
```
Of course the `while` statement they've added will cause the function to loop forever, but the tests on Exercism still passed. The relevant test does fail when run locally (and tried its best to crash my computer with 25GB of output). 

This might be an issue with the platform so apologies if I've posted this in the wrong place, but I suspect its doing some optimisation for testing that eliminates the `println` and then in turn eliminates the empty  `while` loop, which seems more likely to be a Rust specific behaviour.

**Comment by coriolinus** [comment]
Can you link to the exercise showing that the tests completed successfully? 

I'm not aware of anything which would convert a student's `while` to an `if`. Likewise, Rust shouldn't be performing that kind of elimination optimization; both suggested optimizations change observable behavior, and optimizations should not do that.

**Comment by petertseng** [comment]
Here, use mine. https://exercism.org/tracks/rust/exercises/lucians-luscious-lasagna/solutions/petertseng

I used this as my function:

```rust
pub fn remaining_minutes_in_oven(actual_minutes_in_oven: i32) -> i32 {
    loop {
        println!("aaaa");
    }
    0
}
````

Note that I would get a test timeout with only three "a" in the string.

Also note that it says five tests passed. We have six tests.

**Comment by roxgib** [comment]
> Here, use mine.

Thanks, that demonstrates the problem nicely.

> Also note that it says five tests passed. We have six tests.

Digging a bit further it looks like there have been discussions about Rust tests timing out, and an option was provided for the test runner to expect some tests not to complete in time: adding `"test_runner": false` to the `.exercism/config.json`. But that isn't present for this exercise, and I tried it with a different exercise (low-power-embedded-game) and the test failed as expected, so that might not be related. I'm not sure what's special about this exercise or test. Should I file an issue on the main Exericsm repo?

**Comment by roxgib** [comment]
> Note that I would get a test timeout with only three "a" in the string.

Just noticed this comment, and I've now been able to reproduce it on another problem (though it took a lot more that 4 characters). So then it seems that the tests are skipped if they are killed because of excessive data written to stdout. Perhaps other languages will be affected other than Rust - I wasn't able to reproduce it on the Python track, but I suspect that's because Python isn't able to output fast enough to reach the output limit before the timeout.

I'll close this and file an issue on the main Exercism repo.
