### ISSUE TITLE
test for https://exercism.org/tracks/rust/exercises/gigasecond is wrong

### ISSUE THREAD

**Issue by oeawFebe** [exercism/rust#1539]
The assert_eq (expected answer) should be 'dt(2011, 4, 25, 0, 0, 1)'. Same problem for the rest of the another_test
`
fn dt(year: i32, month: u8, day: u8, hour: u8, minute: u8, second: u8) -> DateTime {

        

          

    use time::{Date, Time};

        

          

        

          

    DateTime::new(

        

          

        Date::from_calendar_date(year, month.try_into().unwrap(), day).unwrap(),

        

          

        Time::from_hms(hour, minute, second).unwrap(),

        

          

    )

        

          

}

        

                  

          

#[test]

        

          

fn test_date() {

        

          

    let start_date = dt(2011, 4, 25, 0, 0, 0);

        

          

        

          

    assert_eq!(gigasecond::after(start_date), dt(2043, 1, 1, 1, 46, 40));

        

          

}`

**Comment by petertseng** [comment]
But 2011-04-25 00:00:01 is only one second after 2011-04-25 00:00:00, not one gigasecond. I don't see how `dt(2011, 4, 25, 0, 0, 1)` could possibly be the correct answer. Can you explain
