### ISSUE TITLE
Incorrect calculation, the result here should be 84 instead of 81

### ISSUE THREAD

**Issue by saadjhk** [exercism/rust#1548]
https://github.com/exercism/rust/blob/6c2b8bb7292c5b0f2f2060235e477be0b5e8fa4c/exercises/practice/bowling/tests/bowling.rs#L199

Score = 30 + 28 + 18 + 8

**Comment by petertseng** [comment]
I'm not seeing where the 28 is coming from. The calculation I see is 30 + 25 + 18 + 5 + 3 = 81. What is the reasoning for 28?

**Comment by saadjhk** [comment]
Why are you taking adding 5 from the third frame? It should be 8 thus 28

**Comment by petertseng** [comment]
https://github.com/exercism/rust/blob/main/exercises/practice/bowling/.docs/instructions.md disagrees with that statement.

> A strike is where all ten pins are knocked down by the first throw. The total value of a strike is 10 plus the number of pins knocked down **in the next two throws**

The next two throws after the strike are 10 and 5.

**Comment by saadjhk** [comment]
Oh i got the idea that it includes the entire frame. Thanks for clarification!
