### ISSUE TITLE
Enable merge commits

### ISSUE THREAD

**Issue by petertseng** [exercism/rust#1554]
@ErikSchierboom and/or @iHiD, I hope you can do me the favour of enabling merge commits on this track. Right now, they're disabled because of linear history on the main branch.

**Comment by ErikSchierboom** [comment]
@petertseng I don't have permissions to do so and @iHiD is unavailable this week. He'll do it when he returns next week.

**Comment by kytrinyx** [comment]
@petertseng I've removed the linear history requirement. Holler if I need to tweak anything further!

**Comment by iHiD** [comment]
@ErikSchierboom Could anything be reverting this that we are running as a script? I've done this several times now but it seems to keep changing back.
