### ISSUE TITLE
Unable to submit regex dependency. Proper procedure?

### ISSUE THREAD

**Issue by jtlapp** [exercism/rust#1566]
I'm struggling to submit an exercise that uses regex. My original error was this:

```
error: failed to select a version for the requirement `regex = "^1.6.0"` (locked to 1.6.0)
candidate versions found which didn't match: 1.5.5
location searched: `/opt/test-runner/local-registry` index (which is replacing registry `crates-io`)
required by package `acronym v1.7.0 (/mnt/exercism-iteration)`
perhaps a crate was updated and forgotten to be re-vendored?
As a reminder, you're using offline mode (--offline) which can sometimes cause surprising resolution failures, if this error is too confusing you may wish to retry without the offline flag.
```

After some trial and error, I discovered that by using `regex="=1.5.5"` I could change the error into this:

```
error: failed to select a version for the requirement `aho-corasick = "^0.7.18"` (locked to 0.7.19)
candidate versions found which didn't match: 0.7.18
location searched: `/opt/test-runner/local-registry` index (which is replacing registry `crates-io`)
required by package `regex v1.5.5`
    ... which satisfies dependency `regex = "=1.5.5"` (locked to 1.5.5) of package `acronym v1.7.0 (/mnt/exercism-iteration)`
perhaps a crate was updated and forgotten to be re-vendored?
As a reminder, you're using offline mode (--offline) which can sometimes cause surprising resolution failures, if this error is too confusing you may wish to retry without the offline flag.
```

But `aho-corasick` appears to be a dependency of regex, so I'm not in control over which version gets pulled in. This is my Cargo.toml:

```
[package]
edition = "2021"
name = "acronym"
version = "1.7.0"

[dependencies]
regex = "=1.5.5"
```

What is the proper procedure for submitting projects having dependencies on external crates?

I've  been deleting Cargo.lock, running cargo test, and then doing this:

```
exercism submit Cargo.toml Cargo.lock src/lib.rs
```

**Comment by senekor** [comment]
To resolve such dependency issues, make sure you

- Do not submit the `Cargo.lock` file.
- The version specified in the `Cargo.toml` file should be *lower or equal* to the one mentioned in the error message.
  <details>
  Here, the error message is `candidate versions found which didn't match: 1.5.5`, so the version should not be higher than `1.5.5`.
  </details>
- You should *__not__ to pin the exact version* in `Cargo.toml` by using the equal sign `regex = "=1.5.5"`. Use the regular `regex = "1.5.5"`, it allows cargo to be more lenient with the version.

Feel free to ping me if you still have problems.
