### ISSUE TITLE
(Nitpick) Use `todo!` instead of `unimplemented!`.

### ISSUE THREAD

**Issue by LouisGariepy** [exercism/rust#1598]
Currently, the template for not-yet-completed exercises uses the `unimplemented!` macro. I think `todo!` should be preferred.

The std docs state the `unimplemented` means that it *may or may not* be implemented in the future, while `todo!` means that it *should* be implemented. In this case, for the exercise to work, users *should* implement, so I feel like `todo!` is a better fit.

Furthermore, "todo" has a well-known near-universal meaning, while "unimplemented" may not call the user to action as much.

This is very nitpicky, and maybe you have reasons to use `unimplemented` so feel free to close.

**Comment by felix91gr** [comment]
Is anyone working on this? Because I reckon I could whip it up in an afternoon. I have some spare time right now :)
