### ISSUE TITLE
Macros exercise missing checks

### ISSUE THREAD

**Issue by yulin-physics** [exercism/rust#1610]
More tests could be added for the [Macros exercise](https://exercism.org/tracks/rust/exercises/macros), one specific case I found is when there is no separator between fragments current test set still passes
e.g. 
```
HashMap<u32, u32> = hashmap!(1=>1 1=>1);
```

For the top community solution with the hashmap macro definition:
```
#[macro_export]
macro_rules! hashmap {
    ($( $key: expr => $val: expr )+$(,)?) => {{
         let mut map = ::std::collections::HashMap::new();
         $( map.insert($key, $val); )*
         map
    }}
}
```

**Comment by senekor** [comment]
@yulin-physics This solution already doesn't compile for me locally. It's not the top one in the community solution either, maybe it has changed in the meantime. Maybe you can provide a link?

Either way, I think there actually is already a test for missing commas(?)
https://github.com/exercism/rust/blob/main/exercises/practice/macros/tests/invalid/no-comma.rs

**Comment by yulin-physics** [comment]
@senekor Does look like the "invalid" solution disappeared from community solutions and no longer pass the tests, I'm happy for you to close this issue : )
