### ISSUE TITLE
Say states max value of u64 is 9 quintillion when it should be 18 quintillion

### ISSUE THREAD

**Issue by SethFalco** [exercism/rust#1611]
In the exercise "say" - at the bottom it states the following:

> Add capability of converting up to the **max value for u64: 9,223,372,036,854,775,807**.

However, 9,223,372,036,854,775,807 is the max value of i64, not u64.
The max value of u64 is as written in the test cases, 18,446,744,073,709,551,615.

Can this text be updated?

(I attempted to do a PR for something else before, but seems this repo isn't accepting PRs, so just opening an issue instead.)

**Comment by petertseng** [comment]
We are awaiting anyone to open a pull request fixing this.

**Comment by SethFalco** [comment]
https://github.com/exercism/rust/pull/1621
