### ISSUE TITLE
External Crates in Alphametics

### ISSUE THREAD

**Issue by tomgilligan** [exercism/rust#1645]
Alphametics is under the 'External Crate' concept in syllabus but readme does not mention external crates at all.  I think it's important to learn to be resourceful (eg. if a crate exists that can do the thing you need, go out and find it) but is this what I'm meant to be doing here?  It isn't clear.

**Comment by petertseng** [comment]
External crates for alphametics was added in https://github.com/exercism/rust/pull/225, for this sole reason: there exists **a** solution that uses external crates. Possible solutions for the lack of explanation could be to remove the concept, to add an explanation, or any other solution that reconciles the two. I do not yet have a preference for any particular solution.
