### ISSUE TITLE
Rust Reverse String Problem

### ISSUE THREAD

**Issue by tieje** [exercism/rust#1702]
My solution passes all tests, however, it is not accepted as a solution because [supposedly grapheme is not really part of the standard library in Rust so I used a different crate](https://stackoverflow.com/questions/27996430/reversing-a-string-in-rust)

```rust
use unicode_segmentation::UnicodeSegmentation;

pub fn reverse(input: &str) -> String {
    let res = input.graphemes(true).rev().collect();
    res
}
```

**Comment by remlse** [comment]
@tieje I used the same library as you and my solution passed. Please open a mentoring request on the exercism website if you need help on a specific exercise, mentors can help you more efficiently there.

**Comment by enotskellington** [comment]
pretty silly that the tests pass locally but not in the sites test environment, I'm having the same issue that it can't find the crate

**Comment by senekor** [comment]
The list of available crates in the test runner is here:

https://github.com/exercism/rust-test-runner/blob/main/local-registry/Cargo.toml
