### ISSUE TITLE
Spell checks / Typos

### ISSUE THREAD

**Issue by iChaosren** [exercism/rust#1703]
I use a VS Code extension: [Code Spell Checker](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker)

Going through the exercises I've found a few instances where there are some obvious typos etc.

This issue will probably be excessively pedantic, but I think if anyone else has a few spelling fixes, maybe they can add them to this issue for tracking?

I'll start it off:

[exercises/practice/doubly-linked-list/src/pre_implemented.rs#L1C19-L1C23](https://github.com/exercism/rust/blob/dd0ea4e6c165ebe67d8d2257333cc9bd4e9c6a4d/exercises/practice/doubly-linked-list/src/pre_implemented.rs#L1C19-L1C23) - `thes` -> `this`

**Comment by remlse** [comment]
Hello, thanks for opening this. Do you mind making a pull request for the typos you found?
