### ISSUE TITLE
Question/Possible documentation issue: How to enable features?

### ISSUE THREAD

**Issue by theCalcaholic** [exercism/rust#1704]
[The reverse string exercise](https://exercism.org/tracks/rust/exercises/reverse-string) from the rust track includes a bonus task related to optional dependencies and cargo feature flags.
I have satisfied the test in my local setup, but I fail to find a way to convince exercism to enable the "grapheme" flag during test execution.
What am I missing? :)

---

Cargo.toml
```rust
[dependencies]
 unicode-segmentation = {version = "1.10", optional=true}

[features]
grapheme = ["unicode-segmentation"]

[package]
edition = "2021"
name = "reverse_string"
version = "1.2.0"
```

lib.rs
```rust
#[cfg(feature = "grapheme")]
use unicode_segmentation::UnicodeSegmentation;
pub fn reverse(input: &str) -> String {
    #[cfg(feature = "grapheme")]
    return input.graphemes(true).rev().collect();
    
    input.chars().rev().collect()
}
```

Submitted with: `exercism submit src/lib.rs Cargo.toml`

**Comment by senekor** [comment]
I don't think that's possible. The bonus tests are not supposed to be run online, it's just an additional local challenge. Do you think that should be changed?

*unless*... you add the `grapheme` feature to the [default features](https://doc.rust-lang.org/cargo/reference/features.html#the-default-feature)? I have no idea if that works.

For the future, a mentoring request on the exercise would be a better place for such questions.
