### ISSUE TITLE
One of two-bucket's test case is wrong

### ISSUE THREAD

**Issue by hl-a-k** [exercism/rust#1890]
In this execrism: https://exercism.org/tracks/rust/exercises/two-bucket,
this test case is wrong.
In this case, the right answer is:

<table>
<tr>
<th>step</th><th>size of bucket 1</th><th>size of bucket 2</th>
</tr>
<tr><td>1</td><td>0</td><td>5</td></tr>
<tr><td>2</td><td>0</td><td>0</td></tr>
<tr><td>3</td><td>3</td><td>0</td></tr>
<tr><td>4</td><td>0</td><td>3</td></tr>
<tr><td>5</td><td>3</td><td>3</td></tr>
<tr><td>6</td><td>1</td><td>5</td></tr>
<table> 

```
#[test]
#[ignore]
fn measure_using_bucket_one_of_size_3_and_bucket_two_of_size_5_start_with_bucket_two() {
    let output = solve(3, 5, 1, &Bucket::Two);
    let expected = Some(BucketStats {
        moves: 8,
        goal_bucket: Bucket::Two,
        other_bucket: 3,
    });
    assert_eq!(output, expected);
}
```

**Comment by senekor** [comment]
from the instructions:

> After an action, you may not arrive at a state where the initial starting bucket is empty and the other bucket is full.

This is the case in your step three.

**Comment by hl-a-k** [comment]
Cool man. Thanks a lot.
