### ISSUE TITLE
new test case for Phone Number

### ISSUE THREAD

**Issue by Aryan570** [exercism/rust#1916]
A case like - "223.456abc.7890" should be added to tests cause a code like mine can easily pass the tests  -
`pub fn number(user_number: &str) -> Option<String> {
    let mut v = vec![' ';10];
    let mut tmp = 9;
    for ch in user_number.chars().rev(){
        match ch {
             c @ '0'..='9' =>{
                if (tmp == -1 && c != '1') 
                || (tmp == 0 && c == '1') 
                || (tmp == 0 && c == '0')
                || (tmp == 3 && c == '0')
                || (tmp == 3 && c == '1'){
                    return None;
                }
                if tmp >=0 {
                    v[tmp as usize] = c;
                }
                tmp -= 1;
            }
            _ => continue,
        }
    }
    if v[0] == ' '{return None;}
    Some(v.iter().collect())
}`
test like this should be added (the code above will treat it as a valid number, but it isn't valid) - 
`fn invalid_chars() {
    let input = "223.456abc.7890";
    let output = number(input);
    assert!(output.is_none());
}`

**Comment by senekor** [comment]
@Aryan570 this exercise comes from [problem-specifications](https://github.com/exercism/problem-specifications/tree/main/exercises/phone-number). Please open a forum post about adding the test in that repository. That way, other languages will benefit too.
