### ISSUE TITLE
Wrong source link in the exercise `Reverse String`

### ISSUE THREAD

**Issue by mattcristal** [exercism/rust#1931]
# Issue description

I have started working on the Rust track and noticed that in the exercise Reverse String there is a wrong link at the bottom of the page. See below 👇🏼 

<img width="1512" alt="source_reverse_string" src="https://github.com/exercism/rust/assets/33809495/5f75da2b-3e7d-4b5c-b8b3-b08701908e95">

Specifically, the link refers to JavaScript and not Rust.

See code reference here:
https://github.com/exercism/rust/blob/0b8e1942df6d34fe9a2673754c561544549eb32e/exercises/practice/reverse-string/.meta/config.json#L37

**Comment by senekor** [comment]
This exercise is generated from a central repo, the source url is the same for all language tracks on Exercism.
