### ISSUE TITLE
protein-translation: adds extra codons without mentioning them in instructions

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/rust#1936]
The `protein-translation` exercise adds extra codons without mentioning them in the instructions. This makes it confusing for students. I would personally be in favor of dropping the additional codons that are not mentioned in the instructions, instead of extending the instructions, as the extra codons don't really help teach anything.

**Comment by senekor** [comment]
What about it is confusing to students? The list of codons needed for the tests is passed to the parse function. If they use that correctly, they won't ever notice that the list is extended. They would only notice if they hardcode the list, which I wouldn't want to encourage.

It would make more sense to me to extend the instructions and tests in problem-specifications to cover all codons. I remember we had an issue where there was even a test that prevented the full list of codons from being implemented. ([forum thread](https://forum.exercism.org/t/incorrect-test-in-protein-translation/10616/8)) That wouldn't have happended if we just included all valid codons in the test suite.

**Comment by ErikSchierboom** [comment]
We'll, the instructions state:

```
Below are the codons and resulting Amino Acids needed for the exercise.

| Codon              | Protein       |
| :----------------- | :------------ |
| AUG                | Methionine    |
| UUU, UUC           | Phenylalanine |
| UUA, UUG           | Leucine       |
| UCU, UCC, UCA, UCG | Serine        |
| UAU, UAC           | Tyrosine      |
| UGU, UGC           | Cysteine      |
| UGG                | Tryptophan    |
| UAA, UAG, UGA      | STOP          |
```

But then again, the instructions also do mention:

```
If it works for one codon, the program should work for all of them.
However, feel free to expand the list in the test suite to include them all.
```

It's a bit weird to me, but probably fine.
