### ISSUE TITLE
Tests for protein-translation don't match its README

### ISSUE THREAD

**Issue by jgallagher** [exercism/rust#267]
The [README](http://exercism.io/exercises/rust/protein-translation/readme) for this exercise describe the problem as (roughly) "given a sequence of codons, output the sequence of proteins". However, the tests in `protein-translation` (a) only seem to expect a single protein name from a single codon and (b) talk about codon "compression" which is not mentioned in the README; e.g.,

```rust
fn test_cysteine_tgy() { // "compressed" name for TGT and TGC
    let info = proteins::parse(make_pairs());
    assert_eq!(info.name_for("TGT"), info.name_for("TGY"));
    assert_eq!(info.name_for("TGC"), info.name_for("TGY"));
}

...

fn test_arginine_name() {
    // In arginine CGA can be "compresed" both as CGN and as MGR
    let info = proteins::parse(make_pairs());
    assert_eq!(info.name_for("CGA"), Ok("arginine"));
    assert_eq!(info.name_for("CGN"), Ok("arginine"));
    assert_eq!(info.name_for("MGR"), Ok("arginine"));
}
```

I glanced at a couple other languages' versions of this exercise and saw tests that look much more like the README and don't talk about compressed names ([go](https://github.com/exercism/xgo/blob/master/exercises/protein-translation/protein_translation_test.go), [elixir](https://github.com/exercism/xelixir/blob/master/exercises/protein-translation/protein_translation_test.exs)).

**Comment by petertseng** [comment]
The questions arising from this:

* So does that mean https://github.com/exercism/x-common/issues/268 was incorrect? the nucleotide-codons and protein-translation exercises are not actually the same?
* Should #258 be reverted? Should the nucleotide-codons exercise be un-deprecated in the Rust track, if it is in fact different from protein-translation?
* Should https://github.com/exercism/x-common/pull/532 be reverted? Should the nucleotide-codons exercise be un-deprecated globally, if it is in fact different from protein-translation?
* Should the tests of protein-translation of the Rust track be changed to match the README?
* How can we to decide what the tests should be? We need someone to work on https://github.com/exercism/x-common/issues/577
* Should the [protein-translation readme](https://github.com/exercism/x-common/blob/master/exercises/protein-translation/description.md) be changed to include anything about compression?

**Comment by jgallagher** [comment]
It appears to me that exercism/x-common#268 is correct at a high level:

> both these exercises do the exact same thing: they translate codons to their correct names.

but the two exercises do so quite differently:

* exercism/x-common#37 added the description that is currently the README of protein-translation - converting a sequence of codons into a sequence of names
* exercism/x-common#93 added a description of what the current Rust protein-translation tests check for - converting an individual codon (possibly compressed) into its singular correct name

I would cast a vote for changing the protein-translation Rust track tests to match the README (and what the protein-translation tracks in other languages check for). I have no opinion about reintroducing nucleotide-codons.

**Comment by petertseng** [comment]
Thanks for the initial report and the subsequent evaluation!

I also wish to express no opinion on nucleotide-codons, but I will leave on a note for whoever decides to work on https://github.com/exercism/x-common/issues/577 that they may consider whether to include the old tests of nucleotide-codons. At this point we may consider the discussion of nucleotide-codons deferred to that issue.

For the Turst track, I would also agree that the protein-translation tests should change to match the readme.

**Comment by petertseng** [comment]
> Turst

I managed to butcher Rust.
