### ISSUE TITLE
Prefer to assert_eq!(a, Ok(b)) rather than assert_eq!(a.unwrap(), b)

### ISSUE THREAD

**Issue by petertseng** [exercism/rust#338]
In https://github.com/exercism/rust/pull/292#discussion_r117407845 we decided that asserting equality to an `Ok` gives better error messages than attempting to unwrap (which panics if the observed value is an Err instead of Ok).

We should try to adhere to this.

Find instances of unwrap in asserts by using `git grep 'assert.*unwrap'` (or  `git grep unwrap exercises/*/tests` for a larger hammer) and remove the unwraps by changing the other argument to an `Ok`).

**Comment by nfiles** [comment]
What is the current state of this issue? I identified a number of test files where `.unwrap()` is still being used in the `assert!(...)` statement and would be happy to submit a pull request if this is still desired.

**Comment by petertseng** [comment]
It is still desired. We await a PR.
