### ISSUE TITLE
I don't like having to manually verify that second+later tests are ignored. Can it be automated?

### ISSUE THREAD

**Issue by petertseng** [exercism/rust#352]
As noted in #279, we ignore all tests except the first.

I don't like having to check by hand whether every new exercise submission has done this.

~~Maybe we can automate it~~ We are automating it in https://github.com/exercism/rust/pull/361 by counting the number of `#[ignore]` lines and ensuring that it is exactly one smaller than the number of `#[test]` lines.

~~By suggestion of a contributor (not myself) another possible way to do it is to run `cargo test` and make sure it says `1 passed; 0 failed`. One disadvantage is it involves having to actually compile and run, whereas counting `ignore` and `test` does not.~~

All current exercises have been fixed so they have exactly one fewer `ignore` line than `test` line.

The remaining task is to add it to Travis CI so that future exercises also receive its benefit.

**Comment by petertseng** [comment]
Okay, you're right, another possible way to do it is to run `cargo test` and make sure it says `1 passed`. One disadvantage is it involves having to actually compile and run, whereas counting `ignore` and `test` does not.

**Comment by f3rn0s** [comment]
I had a think.

Here is a shell script that will return whether the given file name is valid.

```sh
file_name="$1"

test_num=$(cat $file_name | grep "\#\[test\]" | wc -l)

ignore_num=$(cat $file_name | grep "\#\[ignore\]" | wc -l)

compare=$(($test_num - 1))

if [ "$compare" -eq "$ignore_num" ]
then
    echo true
else
    echo false
fi
```

**Comment by petertseng** [comment]
Current:

./exercises/bob/tests/bob.rs: Has 25 tests and 23 ignores (should be 24)
./exercises/crypto-square/tests/crypto-square.rs: Has 8 tests and 0 ignores (should be 7)
./exercises/say/tests/say.rs: Has 18 tests and 15 ignores (should be 17)

**Comment by f3rn0s** [comment]
@petertseng Do you want a pull-request to fix this issue?

**Comment by petertseng** [comment]
Updated issue description: The script exists, and current exercises have been fixed. Next step, if the script receives approval and gets merged, is to add it to Travis CI.
