### ISSUE TITLE
Sum of multiple issue

### ISSUE THREAD

**Issue by LukeSkyw** [exercism/rust#360]
The sum of multiples exercise says:
```
Given a number, find the sum of the multiples of a given set of numbers, up to but not including that number.
```

One of the test is:
```rust
#[test]
fn multiples_seven() {
    assert_eq!(30, sum_of_multiples(15, &vec![4, 6]))
}
```
However:
```
4 x 1 =>  4
6 x 1 =>  6
4 x 2 =>  8
6 x 2 => 12
4 x 3 => 12
        ---
         42
```

But the test says 30, like it's ignoring `4 x 3` (the second 12).

**Comment by petertseng** [comment]
Only unique multiples are considered; 12 should only be considered once. This is the intent of the example in https://github.com/exercism/problem-specifications/pull/157. If it should be that the description was not clear about it, or can be made clearer, then it will be time to suggest an improvement to https://github.com/exercism/problem-specifications/blob/master/exercises/sum-of-multiples/description.md.

**Comment by hekrause** [comment]
@petertseng @LukeSkyw 
I made a change in [rust/problem-specifications](https://github.com/hekrause/problem-specifications/blob/master/exercises/sum-of-multiples/description.md) and created a [pull request](https://github.com/exercism/problem-specifications/pull/961).

**Comment by andreyrubtsov** [comment]
I think the task assignment forumulation is OK as it is now.
To me, there no such thing as unique _multiples_, as these _multiples_ are just some of natural numbers: 1,2,3,4....
So saying that they must be unique is the same as saying "natural numbers must be unique".

I think the root of evil is that some folks treat these multiples are independent numbers for each factor, whereas they should not.

**Comment by hekrause** [comment]
So the question is what to do?
I think in the end the addition is helping to understand the exercise better. People may think twice when they read the description. So even if it is still clear without the "unique" word, it will become clear to everybody with it.

**Comment by coriolinus** [comment]
@hekrause Now that the upstream documentation is updated, would you like to create a PR to update the Rust track for this exercise? The actual work involved should be pretty much `configlet generate . --only sum-of-multiples`.
