### ISSUE TITLE
Broken link for "Exercism-specific linting"

### ISSUE THREAD

**Issue by jfunez** [exercism/rust#408]
Hi,

I found that the link pointed in this sentence:
> For the Exercism-specific linting, please see the documentation.

at the README.md ("Verifying your Change" section) raise a 404 error page 

HTH

**Comment by coriolinus** [comment]
Which exercise were you working on when you found this broken link?

**Comment by jfunez** [comment]
Hi @coriolinus 

No specific exercise, the README I mention is that one: https://github.com/exercism/rust

**Comment by coriolinus** [comment]
Thanks for pointing that out! I'll create a PR to fix it shortly.
