### ISSUE TITLE
rna-transcription:   Shouldn't DNA::new() return Result<DNA, Err> ?

### ISSUE THREAD

**Issue by e-max** [exercism/rust#423]
Hi

I found a line `assert!(dna::DNA::new("XXX").to_rna().is_err());` in test suit a little bit confusing. 

What is `DNA::new("XXX")` supposed to return?

By definition in README 
` DNA is a sequence of nucleotides.
The four nucleotides found in DNA are adenine (A), cytosine (C), guanine (G) and thymine (T).
`
So how can `DNA::new("XXX")` return a valid DNA object?  
Or  DNA should be something like `enum DNA { Valid(Vec<Nucleotide>) ,  InvalidDNA}` ? 

Wouldn't be an implementation of `From<&str>` more idiomatic way to create DNA?

**Comment by coriolinus** [comment]
So, you're talking about the [`rna-transcription`](https://github.com/exercism/rust/tree/master/exercises/rna-transcription) exercise, and specifically the test [`handles_completely_invalid_input`](https://github.com/exercism/rust/blob/master/exercises/rna-transcription/tests/rna-transcription.rs#L47-L49), yes? I assume so, though it's useful to confirm. 

Give me a moment to look into it.

**Comment by e-max** [comment]
Yes, exactly! Sorry, I wasn't clear enough.

**Comment by coriolinus** [comment]
Ok, here's how I'd parse the assertion you quoted:

1. `DNA::new()` must have the form `fn new(s: &str) -> Something`, where `Something` has a `to_rna()` method. We can assume from convention that `Something` in this case is likely a `DNA` struct.
2. If the `Something` in question were an `Option<DNA>` or `Result<DNA, ()>`, the test function would need to access the interior value somehow, whether by using `try!()` or `?` or the `map()` method or some other means. However, it used none of these, so we know that it's a simple non-monadic return value.
3. However, you're quite right: by the definition given in the README, some inputs are invalid, and therefore a more natural API would have `DNA::new()` return an `Option` or `Result`.

Where does this leave us?

1. You could write any number of designs for a DNA struct. The one you suggested would work, as would `struct DNA { nucleotides: &'a str, valid: bool }`. Alternately, you could just do [as the example does](https://github.com/exercism/rust/blob/master/exercises/rna-transcription/example.rs#L12-L15) and own a `String` without considering the problem of validation at the DNA level. As far as solving the problem goes, that's all you need.
2. If you're interested in writing a PR to update the exercise to expose a better API, I'd be happy to give you any help you need figuring that process out. Would you like to do that? If so, do you need any help?

**Comment by e-max** [comment]
Thanks for checking this out.  Yes, I realize that using simple wrapper and doing parsing in to_rna() is the simplest way to pass the test.  

What worries me here is that exercise is supposed to teach how to write correct idiomatic Rust code, and this solution doesn't feel like that.  I am not sure what is the right way, because the fact that I am doing exersises shows that I am pretty new in Rust, so it hard for me to judge.

So I guess my question is - What is the right way to implement DNA? 

Just use new(&str) -> Result ?  Implement TryFrom?  Implement FromStr?

Sure I would like to participate.  So, let me send a PR with new(&str) -> Result, non-monadic to_rna() and fixed test. Would you mind to take a look later?

BTW, thank you for showing me the examples - I didn't realize that they exist!  Sometimes , after I submited my solution, I wished to know what would be " the proper way" so solve it.

**Comment by coriolinus** [comment]
Implementing `FromStr` is arguably the most correct way to implement some kind of potentially parseable value, but I don't think we want to go there for this exercise, because the focus of the exercise is elsewhere. We need to balance the pedagogic value of implementing idiomatic APIs with the inherent value of our students' time. As such, I'd be in favor of simply changing the signature of `DNA::new` to return `Option<DNA>`.

I'll absolutely take a look at the PR when it arrives!

np re: examples. We don't put much focus on them, because we want everyone to focus on writing their own implementation first, but they're useful once you have a solution and you want to look at known-correct code. You just need to keep in mind that the examples contain no guarantee that they're elegant, or efficient, or ideal in any sense; they just need to successfully pass all the tests. Incidentally, when you submit your PR, you'll also need to update the example to conform to the new API.

**Comment by derekdreery** [comment]
I came here to submit the same issue. I think it's bad practice to store inconsistent state when the type system allows you to guarantee consistency.

My ideal solution for this problem would be something like

```rust

/// The possible nucleotides in DNA and RNA
#[derive(Debug, Eq, PartialEq, Clone, Copy)]
pub enum Nucleotide {
    Adenine,
    Cytosine,
    Guanine,
    Thymine,
    Uracil
}

impl Nucleotide {
    /// Parses a nucleotode from its character value, if valid.
    fn from_char(ch: char) -> Option<Nucleotide> {
        Some(match ch {
            'A' => Nucleotide::Adenine,
            'C' => Nucleotide::Cytosine,
            'G' => Nucleotide::Guanine,
            'T' => Nucleotide::Thymine,
            'U' => Nucleotide::Uracil,
            _ => { return None; }
        })
    }
}

/// A vector of nucleotides
///
/// Guaranteed that Uracil is not present thanks to `new`.
#[derive(Debug, Eq, PartialEq, Clone)]
pub struct DNA(Vec<Nucleotide>);

impl DNA {
    /// Parse a DNA string, checking it is valid.
    ///
    /// The error value is the first invalid character index (char index, not utf8).
    pub fn new(input: &str) -> Result<DNA, usize> {
        let mut out = Vec::new();
        for (idx, ch) in input.chars().enumerate() {
            match Nucleotide::from_char(ch) {
                Some(Nucleotide::Uracil) | None => { return Err(idx); },
                Some(n) => { out.push(n);  },
            }
        }
        Ok(DNA(out))
    }

    pub fn to_rna(mut self) -> RNA {
        for nuc in self.0.iter_mut() {
            *nuc = match *nuc {
                Nucleotide::Adenine => Nucleotide::Uracil,
                Nucleotide::Cytosine => Nucleotide::Guanine,
                Nucleotide::Guanine => Nucleotide::Cytosine,
                Nucleotide::Thymine => Nucleotide::Adenine,
                Nucleotide::Uracil => unreachable!()
            }
        }
        RNA(self.0)
    }
}

#[derive(Debug, Eq, PartialEq, Clone)]
pub struct RNA(Vec<Nucleotide>);

impl RNA {
    /// Parse a RNA string, checking it is valid.
    ///
    /// The error value is the first invalid character index (char index, not utf8).
    pub fn new(input: &str) -> Result<RNA, usize> {
        let mut out = Vec::new();
        for (idx, ch) in input.chars().enumerate() {
            match Nucleotide::from_char(ch) {
                Some(Nucleotide::Thymine) | None => { return Err(idx); },
                Some(n) => { out.push(n);  },
            }
        }
        Ok(RNA(out))
    }
}
```

**Comment by coriolinus** [comment]
> I think it's bad practice to store inconsistent state when the type system allows you to guarantee consistency.

@derekdreery I very much agree with that sentiment! Your ideal solution looks good to me as well. I'd be happy to accept a PR updating this exercise; it doesn't matter to me whether the primary mover is you, or @e-max, or whether it's a collaborative effort. I just don't have the time to implement such an update myself.

**Comment by derekdreery** [comment]
np, I'll do a PR, I don't think the delta will be too big

**Comment by e-max** [comment]
@derekdreery Yes, exactly!  I got very similar solution for myself, except that I've splitted Nucleotide to RNANucleotide and DNANucleotide  and implemented the `From` trait for all possible transformations like 
char=>Nucleotide,  DNANucleotide=> RNANucleotide,  DNA=>RNA as well as IntoIter.    Final function looked like one line, which is awesome, but all those trait implementations took like 180 lines of code.

**Comment by derekdreery** [comment]
The way you do it should still work with the tests in my PR.

This is an interesting situation: splitting Nucleotide into 2 enums is more correct (in my type system there is still the possibility of errors. However I can prevent errors by controlling the construction of those types. Fully using the type system means writing more code. I'm not sure there's a right answer to which is better! :)

**Comment by coriolinus** [comment]
I don't believe that there exists a correct answer as to which approach is
better. I do believe that good problem design permits both approaches.
