### ISSUE TITLE
Additional test for reverse-string

### ISSUE THREAD

**Issue by rrredface** [exercism/rust#428]
There is a method of passing all the tests in the reverse-string excercise that fails completely in other situations. This is the solution I came up with, and realized afterwards that it will fail to reverse wide characters.
```rust
pub fn reverse(source: &str) -> String {
    if source == "" { return source.to_owned() }
    let mut rev = source.to_owned();
    let len = rev.len() - 1;
    let mut i = 0;
    while i < len / 2 {
        unsafe { rev.as_bytes_mut().swap(i, len - i); }
        i += 1;
    }
    rev
}
```
If all characters in the string provided are exactly 1 byte, this works as expected. However, if `source` was, for example, "運動" it fails because there are characters of multiple bytes. Obviously I'm aware this is a bad solution, however, I think it would be beneficial to have a test that prevents students from making this mistake and not realizing that it's a mistake at all. So, I propose that the following test is added:
```rust
#[test]
// wide characters
fn test_wide() {
    process_reverse_case("運動", "動運")
}
```

**Comment by coriolinus** [comment]
Per problem-specifications#428, we typically do not test non-ASCII cases,
except where it is specifically applicable to the problem and not
incredibly tedious.

I believe that non-ASCII input is specifically applicable to this problem,
and not incredibly tedious in Rust. I'd therefore be inclined to endorse a
PR which added that case to this exercise.

**Comment by petertseng** [comment]
I agree that it does not add undue additional burden, because I would guess (hoping I'm not wrong) that the intersection of the set of students who would be confused the extra addition and the set of students who would try an approach that would not work is very small. Seeing that https://www.rust-lang.org/ prominently features many multi-byte characters in its introductory code snippet, adding a test would match that intent.

**Comment by coriolinus** [comment]
Out of curiosity, do the strings "運動" and "動運" have any particular meaning? I believe them to be Chinese as opposed to Japanese, but that's about as far as my knowledge goes. 

While the particular wide characters chosen don't matter as such, it would be a bonus if a case were chosen such that reversing the characters still produced meaningful output; a "swap" <-> "paws" situation.

**Comment by ijanos** [comment]
Please keep in mind that unicode is really complicated and the most "human" reversing is based on graphmeme clustering, which is available on crates.io but not built into the language.  https://crates.io/crates/unicode-segmentation

Using only the standard library to reverse a unicode strings could produce surprising results. See the output of this playground example: https://play.rust-lang.org/?gist=c5eec06ad895a8f02ebdd8a63d64f04c&version=stable 

If we include a similar string in a test what should the output be? We could just ignore combining characters of course or expand the hints with a bonus test to push eager students to learn about graphmeme cluster based reversing, like this: 

> Test your code on this string uüu and see what the result is, try to write function that properly reverses the string, hint: grapmeme clusters

**Comment by coriolinus** [comment]
Good point. I think my instinct would be to provide a test with wide but
not combining characters, and also add the note you suggest with the
combining character example. That way the exercise can be completed without
an external crate or complicated code, but motivated students still have a
more complicated example available.

**Comment by rrredface** [comment]
> Out of curiosity, do the strings "運動" and "動運" have any particular meaning? I believe them to be Chinese as opposed to Japanese, but that's about as far as my knowledge goes.
 
They're technically Chinese characters, but in Japanese they mean "exercise" at least forward. I've looked and they don't seem to have any meaning backwards, and it would be difficult for me to pick out a word that has a meaning both forward and backward since my knowledge of the language is *very* basic.

> I believe that non-ASCII input is specifically applicable to this problem, and not incredibly tedious in Rust. I'd therefore be inclined to endorse a PR which added that case to this exercise.

Then should I see about reading up on the PR guidelines and making one? Also, if I were to include the aforementioned note about the string `uüu`, where would that ideally reside? In a comment above/below the function in lib.rs would be my first guess.

I also have a quick question. I'm very new to contributing to projects like this. In the future would it be easier to just make a pull request to begin with and have that be discussed rather than opening an issue first?

**Comment by coriolinus** [comment]
What would you think of using "子猫", which is a palindrome when written in kana? The choice of string is yours, but I think it might be cute to include some bit of wordplay. 

> Then should I see about reading up on the PR guidelines and making one?

Yes, please.

> if I were to include the aforementioned note about the string uüu, where would that ideally reside?

I wouldn't put it in a comment; `.meta/hints.md` would be my preference for location. This gets combined with some other information by the `configlet` tool to generate `README.md`. 

> would it be easier to just make a pull request to begin with?

When you have a concrete idea for an improvement such as this, yes, it's a bit easier to just begin with a PR. It's no problem to begin with an issue instead, though, particularly if you don't have a specific improvement in mind.
