### ISSUE TITLE
series: expected result values for too long and zero length tests appear swapped

### ISSUE THREAD

**Issue by tjkierzkowski** [exercism/rust#439]
I noticed that the tests used in the series exercise to validate if the series function is too long and the test for if the series function has a zero length appear to be incorrect.  For instance, the test `test_with_zero_length` should likely have an expected value of `vec![""]` instead of a Vector with `_len` number of empty strings (see [this line](https://github.com/exercism/rust/blob/3d40647b0df2c2b0e182e9b49d1358f7c3993ca6/exercises/series/tests/series.rs#L6)).  I wrote and submitted the code to make the current tests pass but it seems like the expected cases may have been swapped by mistake.  I can imagine this would break a quite a few people's exercism submissions for this exercise (roughly 141 as of this comment). I wanted to reach out on what to do with this or to get some clarification on if this is an issue. I'm not sure this test is broken in other language tracks version of the series exercise. The Python tests throw a ValueError exception and I haven't looked at others just yet.  The fix would be simple and I'm willing to submit a pull request for this.  Thanks for curating this track!

**Comment by petertseng** [comment]
Well I'll think about it from the point of view of, say, a length 3 series "abc"

There are three subseries of length 1: "a", "b", "c"
There are two subseries of length 2: "ab", "bc"
There is just one subseries of length 3: "abc"

So the values that make sense if we extrapolate would be:

There are zero subseries of length 4.
There are four subseries of length 0.

What I see in https://github.com/exercism/rust/blob/3d40647b0df2c2b0e182e9b49d1358f7c3993ca6/exercises/series/tests/series.rs currently matches this pattern; in a series of length 5 there are zero subseries of length 6 and six subseries of length 0. https://github.com/exercism/rust/pull/402#discussion_r153480774 agrees with this interpretation.

I'd be willing to hear arguments for why they should be changed.

**Comment by tjkierzkowski** [comment]
You're absolutely right, and I didn't think of it that way.  You helped clarify my understanding of the edge cases of the problem. Sorry I opened this non-issue and contributed to some noise on the issues. Thank you detailed explanation!

**Comment by petertseng** [comment]
It is all right! We are happy to help. Therefore, apology accepted, and do not be afraid to ask more questions in the future.
