### ISSUE TITLE
Remove underscores from exercise stub 

### ISSUE THREAD

**Issue by cbzehner** [exercism/rust#442]
Per discussion that began on https://github.com/exercism/rust/pull/438. 

Some of the exercise stubs currently use `_` as a parameter for their input. This is confusing for beginners since `_` binds any pattern (it serves as the default case in matches) and is prefixed to a variable to suppress an underscore.

This is currently used in function stubs as a way of reducing the initial number of compiler warnings encountered on the Rust track and most of these stubs have a body of `unimplemented!()` and nothing more.

However, in most cases we should be able to easily turn the function input into a regular parameter _and_ avoid compiler warnings by referencing it in the body of our function. So the normal stub:
```
pub fn exercise(_: &str) -> bool {
  unimplemented!()
}
```
becomes
```
pub fn exercise(input: &str) -> bool {
  unimplemented!("There's an easy way to reference your input variable: {}", input)
}
```

A quick `rg -e 'pub fn \w+\(_' --count | sort | cut -f 1 -d '/'` shows which exercises are affected (caveat: this might miss some).
* [ ] alphametics
* [ ] book-store
* [ ] crypto-square
* [ ] decimal
* [ ] diffie-hellman
* [ ] isbn-verifier
* [ ] poker
* [ ] reverse-string
* [ ] series

**Comment by petertseng** [comment]
I looked for all multi-line stub definitions:

```
$ git grep fn exercises/*/src/lib.rs | grep -v '{'
exercises/two-bucket/src/lib.rs:pub fn solve(capacity_1: u8,
```

I verified that two-bucket has no underscores.

There are two categories of things we'd like to remove: plain underscore `_` and underscore-prefixed names such as `_input`.

The former:

```
$ git grep 'fn.*(_:'    (03-17 22:30)
exercises/alphametics/src/lib.rs:pub fn solve(_: &str) -> Option<HashMap<char, u8>> {
exercises/book-store/src/lib.rs:pub fn lowest_price(_: &[usize]) -> usize {
exercises/crypto-square/src/lib.rs:pub fn encrypt(_: &str) -> String {
exercises/decimal/src/lib.rs:    pub fn try_from(_: &str) -> Option<Decimal> {
exercises/poker/src/lib.rs:pub fn winning_hands<'a>(_: &[&'a str]) -> Option<Vec<&'a str>> {
$ git grep 'fn.*,_:'    (03-17 22:31)
zsh: exit 1     git grep 'fn.*,_:'
```

And it's now safe to say the other exercises identified above are cases of the latter.

**Comment by petertseng** [comment]
Explanation of closing: In #474 we agreed to split this into two issues. This issue designates all variable whose names are a single underscore. A separate issue (#476) designates all underscore-prefixed issues.
