### ISSUE TITLE
book-store should use integer number of cents, not floating-point numbers.

### ISSUE THREAD

**Issue by petertseng** [exercism/rust#450]
As suggested in https://github.com/exercism/problem-specifications/issues/964 and ratified in https://github.com/exercism/problem-specifications/pull/1089, book-store should use integer number of cents. The Rust track should do the same.

TASK:

* Change the tests in https://github.com/exercism/rust/blob/master/exercises/book-store/tests/book-store.rs to use integer number of cents instead of floating-point numbers by multiplying by 100. The reason we do this is to avoid testing exact floating-point equality, a practice we do not want to encourage by example. For example, `8.0` should change to `800`.
* Change the stub in https://github.com/exercism/rust/blob/master/exercises/book-store/src/lib.rs to use an integer type instead of `f64`, so that students downloading this exercise will receive a stub listing the correct type.
* Change the example in https://github.com/exercism/rust/blob/master/exercises/book-store/example.rs to perform calculations in terms of integers, so that we can verify that the changed tests were in fact changed correctly.
* Increase the version in https://github.com/exercism/rust/blob/master/exercises/book-store/Cargo.toml#L3 to match https://github.com/exercism/problem-specifications/blob/master/exercises/book-store/canonical-data.json#L3 so that we can keep track of the fact that we are up to date.

**Comment by coriolinus** [comment]
Oops, didn't even think to wait for someone to tackle this as a first issue.

**Comment by petertseng** [comment]
Certainly no restrictions on it being first-timer only. It all depends on who has the time. I'm sure there are other possible tasks to generate.
