### ISSUE TITLE
Pig latin README may need to be updated

### ISSUE THREAD

**Issue by shingtaklam1324** [exercism/rust#453]
The problem specification has updated on Feb 22. The overall message of the description is the same, but the wording has changed. 

[diff](https://github.com/exercism/problem-specifications/commit/577e3eaa7d18940f033a32a39b9998a765a3f45a#diff-54ded3ed04fb524402af94d680444ad1)

**Comment by petertseng** [comment]
I request that the person who submits the PR to update the README please include `https://github.com/exercism/problem-specifications/pull/1171` in the commit message, so that it is possible to tell from the logs where the change came from.
