### ISSUE TITLE
react: Add a test for `remove_callback` where the cell doesn't exist

### ISSUE THREAD

**Issue by petertseng** [exercism/rust#465]
TASK: 

Please add a test to https://github.com/exercism/rust/blob/master/exercises/react/tests/react.rs that tests calling `remove_callback` where the specified cell doesn't exist.

Feel free to refer to tests entitled error_setting_a_nonexistent_input_cell and error_creating_compute_cell_if_input_doesnt_exist for examples on how to refer to a nonexistent cell.

---

Note that I do not think this test necessarily makes sense to add to https://github.com/exercism/problem-specifications/blob/master/exercises/react/canonical-data.json , since most languages are able to return references to cells, whereas Rust must use cell IDs only. Thus, all tests with nonexistent cells (there are a few others) that are present in the Rust track are not present in the canonical data.

I think we probably should, especially if we're going to make it an explicitly specified error case (#464)

**Comment by coriolinus** [comment]
Agree that we should: if we explicitly specify an error case, we should ensure that it is generated appropriately.
