### ISSUE TITLE
isogram/src/lib.rs is empty

### ISSUE THREAD

**Issue by BartMassey** [exercism/rust#505]
Should probably be template source in `isogram/src/lib.rs`. I'm going to guess

```Rust
pub fn check(candidate: &str) -> bool {
    unimplemented!("Is {} an isogram?", candidate);
}
```

**Comment by petertseng** [comment]
I don't see any problems with this proposal, so I say that is a good guess.

**Comment by BartMassey** [comment]
Thank you!
