### ISSUE TITLE
run-length-encoding/src/lib.rs is empty

### ISSUE THREAD

**Issue by BartMassey** [exercism/rust#507]
Hate to be a broken record here. Shall I just file one issue for the rest of these and call it a day?

run-length-encoding/src/lib.rs contains no templates. Suggest

```Rust
pub fn encode(source: &str) -> String {
    unimplemented!("Return the run-length encoding of {}.", source);
}

pub fn decode(source: &str) -> String {
    unimplemented!("Return the run-length encoding of {}.", source);
}
```

**Comment by BartMassey** [comment]
Actually, second template should read `"Return the run-length decoding of {}."`

**Comment by petertseng** [comment]
Other than the fact that the `unimplemented` message for `decode` should mention decoding (not encoding), I see no problems with the suggestion.

> Shall I just file one issue for the rest of these and call it a day?

That depends on what the goal is. I don't want to presume to know what the goal is, so I will refrain from advising until I hear the goal.
