### ISSUE TITLE
luhn has no template

### ISSUE THREAD

**Issue by BartMassey** [exercism/rust#513]
`luhn/src/lib.rs` should be

```Rust
/// Check a Luhn checksum.                                                      
pub fn is_valid(code: &str) -> bool {
    unimplemented!("Is the Luhn checksum for {} valid?", code);
}
```

I'll likely submit a rollup patch for all of these in the next day or two if nobody starts to work them first. Shouldn't really have spammed the issue tracker with them, probably.

**Comment by coriolinus** [comment]
No worries. Thanks for contributing!

**Comment by coriolinus** [comment]
The following command locates all exercises for which `lib.rs` does not exist:

```shell
$ find exercises/ -maxdepth 1 -mindepth 1 -type d -exec ls {}/src \; | grep -v lib.rs
```

As it happens, the list is empty.
