### ISSUE TITLE
Leap Exercise stub uses CR/LF instead of LF

### ISSUE THREAD

**Issue by MggMuggins** [exercism/rust#518]
Two things I noticed in the leap exercise: 
- The stub `lib.rs` uses windows-style line endings, while every other file I've yet seen uses Unix.
- The tests pass for a solution that is just `year % 4 == 0`. That is not really an accurate way to tell if a year is a leap year or not. The readme could probably elaborate on the definition of a leap year a little more thoroughly (not just examples from the tests), and the tests could be more complete to include one of the exceptions.
This doesn't seem like a particularly challenging issue. I might open a PR if I decide I have time.

**Comment by coriolinus** [comment]
- We'd be happy to receive a PR switching the line endings to LF for consistency.
- [This test](https://github.com/exercism/rust/blob/master/exercises/leap/tests/leap.rs#L14-L18) ensures that you need something a _bit_ more complicated than `year % 4 == 0`. That said, there aren't a ton of tests for this exercise, so we'd be happy to receive a PR adding more.

**Comment by MggMuggins** [comment]
I may do that, many of the stubs have CR-LF endings.
I have since realized the "run the first test, then remove ignores to run more" workflow. I'm not sure that is a good way to go. It takes some time to remove all the ignores on larger test suites, and it increases the barrier to entry for beginners. We could open a new issue for that if you'd like.

**Comment by coriolinus** [comment]
The workflow of incrementally removing ignore lines is not likely to change; that's a pretty fundamental part of how exercism works. Feel free to open another issue discussing it, but I'd be surprised if it gained much traction.

For what it's worth, I also prefer to run all tests from the beginning. I wrote a little script to make that faster:

```shell
$ cat get-rust.sh
exercism fetch rust
for test in */tests/*.rs; do
   sed -i -e '/#\[ignore\]/{
      s/#\[ignore\]\s*//
      /^\s*$/d
   }' $test
done
```

**Comment by petertseng** [comment]
> run all tests from the beginning. 

To help me achieve this purpose, I like to run `cargo test && cargo test -- --ignored`.
