### ISSUE TITLE
Authors in Cargo.toml

### ISSUE THREAD

**Issue by christianpoveda** [exercism/rust#524]
Several exercises (20 of them) have an author in their Cargo.toml files. Of course no one submits its Cargo.toml file but I think it would be better if that field was omitted. The exercises are:

```
accumulate/Cargo.toml
4:authors = ["sacherjj <sacherjj@gmail.com>"]

binary-search/Cargo.toml
4:authors = ["<marco.stahl@mailbox.org>"]

book-store/Cargo.toml
4:authors = ["Peter Goodspeed-Niklaus <peter.r.goodspeedniklaus@gmail.com>"]

crypto-square/Cargo.toml
4:authors = ["Peter Goodspeed-Niklaus <peter.r.goodspeedniklaus@gmail.com>"]

clock/Cargo.toml
4:authors = ["sacherjj <sacherjj@gmail.com>"]

decimal/Cargo.toml
4:authors = ["Peter Goodspeed-Niklaus <peter.r.goodspeedniklaus@gmail.com>"]

macros/Cargo.toml
4:authors = ["Peter Goodspeed-Niklaus <peter.r.goodspeedniklaus@gmail.com>"]

nth-prime/Cargo.toml
4:authors = ["sacherjj <sacherjj@gmail.com>"]

nucleotide-codons/Cargo.toml
4:authors = ["Peter Minten <peter@pminten.nl>"]

palindrome-products/Cargo.toml
4:authors = ["Kirill Meng <kirill.meng@hotmail.de>"]

pig-latin/Cargo.toml
4:authors = ["sacherjj <sacherjj@gmail.com>"]

poker/Cargo.toml
4:authors = ["Peter Goodspeed-Niklaus <peter.r.goodspeedniklaus@gmail.com>"]

prime-factors/Cargo.toml
4:authors = ["sacherjj <sacherjj@gmail.com>"]

proverb/Cargo.toml
4:authors = ["sacherjj <sacherjj@gmail.com>"]

protein-translation/Cargo.toml
4:authors = ["Peter Minten <peter@pminten.nl>"]

pythagorean-triplet/Cargo.toml
4:authors = ["sacherjj <sacherjj@gmail.com>"]

reverse-string/Cargo.toml
4:authors = ["Peter Goodspeed-Niklaus <peter.r.goodspeedniklaus@gmail.com>"]

run-length-encoding/Cargo.toml
4:authors = ["zombiefungus <divmermarlav@gmail.com>"]

rotational-cipher/Cargo.toml
4:authors = ["Chad Baxter <cbaxter@mail.umw.edu>"]

say/Cargo.toml
4:authors = ["sacherjj <sacherjj@gmail.com>"]

```

**Comment by coriolinus** [comment]
The argument in favor of removing the field, as I understand it, is to provide a blank slate for students which mirrors what they'd get if they ran `cargo new`. The argument against is that by providing attribution for the person who adds an exercise, we hope to encouraged people to add exercises.

As a repeat offender in the list above, I have to recuse myself from actual decision-making on this issue.

**Comment by ijanos** [comment]
I have a soft opinion that we should leave that field empty, I feel GitHub provides attribution for those who need it and the exercises should remain a blank slate so a student can own their creation. 

I did not check what other language tracks do however and I will accept what the others feel appropriate here.

**Comment by christianpoveda** [comment]
I share @ijanos opinion. Github's PRs should be "enough" attribution. Haskell's track (I'm talking about haskell because Haskell depdendency manager is similar to Cargo) does not have any authors in its `package.yaml` file.

Even then, it would be possible to have a "Contributors/Authors" section in the Readme I guess.

**Comment by petertseng** [comment]
as a maintainer who may have explicitly been asked for an opinion, I explicitly check in with No Opinion.

I believe that means it's time to say an interested party should submit a PR removing all the lines.

Please advise me on how this all works, I am not familiar enough with all the rules and conventions that would apply in the event of a previous contributor who added such a line saying "Hey! My contribution of that exercise was conditional on that line being present! I revoke my contribution immediately!"

**Comment by christianpoveda** [comment]
Well given that I opened this issue I volunteer to do the PR if the decision is to remove or move the authors to other file

**Comment by coriolinus** [comment]
Of the maintainer votes in the last 10 days, we have one who refused to vote, one who explicitly vote for no opinion, and one who agreed that we should remove those names.

@christianpoveda if you're willing to open that PR to remove the names, I believe that we've collectively decided in favor of removing them. What would be truly excellent would be if in that PR you added a travis check which ensured that no exercise re-added them. You can look at the [`_test`](https://github.com/exercism/rust/tree/master/_test) directory for examples of the checks we currently have in place. That is, however, an optional bonus step; it's not required.

**Comment by christianpoveda** [comment]
ok will work on it
