### ISSUE TITLE
Optional tests: Discuss conditional compilation vs comments

### ISSUE THREAD

**Issue by petertseng** [exercism/rust#536]
In #533 conditional compilation is used. In binary-search and triangle comments are used. Discuss whether any of these should change

**Comment by coriolinus** [comment]
I'd say that conditional compilation and commented optional tests are
equivalently difficult for the student; I don't see any particular benefit
in favor of either.

If we choose to validate that examples can solve all optional tests, then
conditional compilation becomes much easier for us to verify. However, I am
inclined against having us validate that examples can solve optional tests.

My overall impression is that the strongest argument in favor of us taking
action is simply to ensure that we're consistent across the entire track.
That's a pretty low-priority motivation in my mind.

**Comment by petertseng** [comment]
Neither maintainer participating in this issue was able to find a strong reason to change the status quo.
