### ISSUE TITLE
Optional tests: Should we make sure some example solution can pass

### ISSUE THREAD

**Issue by petertseng** [exercism/rust#537]
There's currently no assurance of any optional tests, no matter whether they're commented or behind conditional compilation. Should that change

**Comment by coriolinus** [comment]
I guess the answer here depends on what the purpose of the example solution
is.

If the purpose of the example is to demonstrate that nobody's written a
malicious exercise which requires impossible effort from the students, i.e.
"Solve the Traveling Salesman Problem in Polynomial Time", then yes: we'd
need to verify that the example can solve all tests.

If the purpose of the example is to provide a resource for students who are
having trouble and want to see how someone else implemented the problem
they're on, then no, I don't think it's necessary for the example to be
able to handle the optional tests.

I don't know what the purpose of the example is, canonically. From the
level of attention put into reviewing exercise submissions both here and in
the problem-specifications repository, I have to imagine that the purpose
of the example tends more toward the latter than the former. If that
interpretation is correct, then we don't need to put any effort into
ensuring that optional tests are solved.

As a practical matter, I suspect that we'd have to forbid optional tests
from being simply commented out--it's just too hard a problem to identify
optional tests in comments. Instead, we could put a file in .meta listing
the feature flags with which an exercise can be compiled, and then ensure
that the test runner supplied all of them when performing its checks.

However, my instinct is that we just don't need to.

**Comment by petertseng** [comment]
> what the purpose of the example is, canonically

Unfortunately https://github.com/exercism/docs/blob/master/language-tracks/exercises/anatomy/README.md#reference-solution (permalink to the commit I see today https://github.com/exercism/docs/blob/03adceb68dc1c3b06c9158ac179a186b16270428/language-tracks/exercises/anatomy/README.md#reference-solution ) is not helpful on this matter.

> The solution does not need to be particularly great code, it is only used to verify that the exercise is coherent.

I could say my recourse is to make my own statement on what the example should be, I suppose. It is not ideal to be in contravention of Exercism's published standards, but at least if I write my standards down someone can evaluate whether the published standards should change.

In my head, the example solution fits both proposed purposes here

> demonstrate that nobody's written a malicious exercise which requires impossible effort from the students

After all, it's what Travis CI checks

>  provide a resource for students who are having trouble and want to see how someone else implemented the problem they're on

I have doubts about this since the example is not publicly visible anywhere on the Exercism site; students must visit this repository to find it.

Nevertheless, I try to make examples reasonably good examples of code. It's in the name, after all. Although the name isn't `good_example.rs` versus `bad_example.rs`, it'd probably still reflect badly if it were bad code.

While all this seems to say I'd want to test the optional tests, there's a significant thought I'd have to address before wanting to do that:

Writing `example.rs` to pass optional tests will significantly increase its complexity (especially true of the optional test of triangle). Students may look at such an example and wonder why all the complexity is there. Implicit in this is that I think a simpler example is a better example.

I do not want myself or any contributor to put effort toward testing optional tests before this is addressed, and addressing this is not high enough priority to me that I wish to take up an open issue with this. Feel free to continue discussion if any solutions make themselves apparent.
