### ISSUE TITLE
Add documentation stating which file should be submitted upon exercise completion

### ISSUE THREAD

**Issue by bzm3r** [exercism/rust#539]
It is unclear which file I am supposed to select for submission. The `src/lib.rs` under a particular exercise module's folder? Or something else? The documentation [here](http://exercism.io/languages/rust/about) can then be updated to clarify this (I can submit a pull request).

**Comment by coriolinus** [comment]
Submit whatever files you did work on. Generally speaking, that'll be `src/lib.rs`, but if (for example) you used some external crates, you may also wish to submit `Cargo.toml`.

**Comment by coriolinus** [comment]
We're happy to review PRs. The source document for your linked page is in `docs/ABOUT.md`.

**Comment by ZapAnton** [comment]
`docs/ABOUT.md` does not contain `Try it!` section. Perhaps it is some other exercism-wide template?

**Comment by ZapAnton** [comment]
@coriolinus, since [this PR](https://github.com/exercism/exercism.io/pull/3792) has been merged, could this issue be closed? Or do you want to see some Rust-specific instructions in the `ABOUT.md`?

**Comment by coriolinus** [comment]
Works for me. Closing via https://github.com/exercism/exercism.io/pull/3792.
