### ISSUE TITLE
configlet fmt check: Should only run when a JSON file is changed

### ISSUE THREAD

**Issue by petertseng** [exercism/rust#544]
If it runs unconditionally, a new `configlet` release can cause unrelated failures on PRs that touch nothing related to the JSON files, but we run the risk of being out of date.

Similar tradeoff that we made when checking READMEs: It only checks the exercises that were changed in PR.

**Comment by coriolinus** [comment]
I think that it's reasonable to only run configlet fmt when the JSON file
changes; it's worse to have unrelated exercises triggering configlet
failures than to have them get out of date.

**Comment by petertseng** [comment]
Title rephrased to be from the form of a question to a declaration of what should be.
