### ISSUE TITLE
Ignored tests handling

### ISSUE THREAD

**Issue by ZapAnton** [exercism/rust#545]
Right now the README.md file in some exercises states that the only way to run ignored tests is to manually remove #[ignore] flag from test file. 

Perhaps README could also mention that you can run all ignored tests with `cargo test -- --ignored`
and any individual test with `cargo test test_name`?

Maybe also provide a [link](https://doc.rust-lang.org/book/second-edition/ch11-02-running-tests.html "Running tests in Rust") about testing along with help-page, modules and cargo links?

**Comment by coriolinus** [comment]
I'd be happy to review a PR adding those notes to the README.

**Comment by ZapAnton** [comment]
I would do a PR, just need some directions - is there a single template for a README, 
or should I edit READMEs for every exercise?

**Comment by coriolinus** [comment]
You'd need to perform two steps:

1. Update [`config/exercise_readme.go.tmpl`](https://github.com/exercism/rust/blob/master/config/exercise_readme.go.tmpl) to update the template
2. Run `configlet generate .` from the track root to update all the individual READMEs.

Ideally, these two steps should be performed in individual commits.

If in the course of the PR we end up iterating a few times over the exact verbiage used, we'll most likely end up squashing everything in the end anyway, so don't worry too much about continuously rebasing things.

**Comment by coriolinus** [comment]
Note: if you don't yet have configlet, you can get it on unixy systems by running `bin/fetch-configlet`.

**Comment by ZapAnton** [comment]
It seems that configlet cannot generate README for `twofer` problem - it looks for `twofer` problem metadata in `problem-specifications` and cannot find it since the problem name is actually `two-fer`.

I can manually rename the directory, but won't it break the problem data?

**Comment by coriolinus** [comment]
Huh. I guess it's been a while since we regenerated that README!

Just rename the twofer directory in your local copy of
problem-specifications, and don't push that change. Please don't change the
name of the twofer exercise in our exercise list.
