### ISSUE TITLE
Some exercises are missing templates in lib.rs

### ISSUE THREAD

**Issue by tushartyagi** [exercism/rust#551]
I guess the issue is self explanatory. There are some exercises which are missing the template/function stub in the `lib.rs` file. For example, the `lib.rs` of [etl](https://github.com/exercism/rust/blob/master/exercises/bracket-push/src/lib.rs) is empty. #512 is about the same issue and it is still open.

I can raise PRs as and when I come across such exercises. But wanted to understand what would go inside the `unimplemented!()` description? Will the best description do, or are we following any pattern.

I've created a PR for this one: https://github.com/exercism/rust/pull/550

**Comment by coriolinus** [comment]
The full list of exercises with empty stub files can be generated with 

```sh
find exercises/ -name "lib.rs" -empty | cut -d'/' -f2
```

As of right now, that list is

- [ ] accumulate
- [ ] acronym
- [ ] allergies
- [ ] anagram
- [ ] binary-search
- [ ] bracket-push
- [ ] circular-buffer
- [ ] clock
- [ ] custom-set
- [ ] dominoes
- [ ] etl
- [ ] hexadecimal
- [ ] luhn-from
- [ ] luhn-trait
- [ ] minesweeper
- [ ] nucleotide-codons
- [ ] nucleotide-count
- [ ] parallel-letter-frequency
- [ ] phone-number
- [ ] pig-latin
- [ ] protein-translation
- [ ] queen-attack
- [ ] rectangles
- [ ] rna-transcription
- [ ] robot-name
- [ ] roman-numerals
- [ ] rotational-cipher
- [ ] sieve
- [ ] sublist
- [ ] tournament
- [ ] triangle
- [ ] wordy

In general, track maintainers will not add stubs for these exercises, but we're happy to review PRs which add appropriate stubs.

**Comment by neganp** [comment]
I also noticed this. As discussed in #542, there are some exercises where adding even a boilerplate template with the appropriate types would take something away from the exercise. Even if the tests dictate what types you need to use, I think reading the tests and figuring out what you need is a useful exercise. In some of these cases, a little note explaining what you're being asked to do might be more appropriate. 

That said, there are some exercises (`custom-set` is one I worked through recently) where you have to write out a whole bunch of boilerplate before you can get your first test to run. In that case, I might push a little harder for a template, especially if there are other exercises where you're doing the type-sleuthing yourself.

**Comment by petertseng** [comment]
When the time comes to close this issue, I suggest that be done with ensuring that all exercises have a stub (except for any exceptions that we designate). For example, perhaps that would be done via a change to https://github.com/exercism/rust/blob/master/_test/ensure-stubs-compile.sh and/or https://github.com/exercism/rust/blob/master/_test/ensure-lib-src-rs-exist.sh

**Comment by coriolinus** [comment]
Agree: once every exercise has a stub or a reason otherwise, it would be very practical to build a check into the CI which ensures that we retain that status.
