### ISSUE TITLE
Exercise rename broke two-fer on the mentors-beta site

### ISSUE THREAD

**Issue by iHiD** [exercism/rust#564]
Hello lovely Rust maintainers. 

[This commit](https://github.com/exercism/rust/commit/573c3a56e7d0f8d9385f507a584b0c4fc1305a76) broke `two-fer` on the mentors-beta site. 

That's entirely not your fault or your problem, and it's something we'll fix, but I just wanted to raise an issue so that anyone getting 500 errors trying to download these exercise knows that this is being managed elsewhere. I'll close this when it's fixed (probably Thursday). Thanks!

**Comment by coriolinus** [comment]
Thanks letting us know. Given that the only renamed exercise in that commit
was also deprecated in the same commit, I hope that few users will be
affected.

**Comment by iHiD** [comment]
This should be fixed in the new version now. Thanks :)
