### ISSUE TITLE
simple-cipher: validity of 'encode_random_uses_randomly_generated_key' test

### ISSUE THREAD

**Issue by ZapAnton** [exercism/rust#569]
The `encode_random_uses_randomly_generated_key` test checks the randomness of generated keys, by generating 100 keys, placing them into `HashSet` and then checking, if the length of the set is 100. 

While the probability of 2 or more generated keys  being equal is extremely low, it is still a probability, on which test completion is based. That does not sound like a solid test case.

Perhaps there is another way to check randomness of generated keys? 

And should it really be checked, since it is basically checking if the `rand` crate is really working, which requires  much more sophisticated tests?

**Comment by coriolinus** [comment]
The point of that test is not really to validate that the rand crate is
working properly. It is to make it impractical for students to hardcode
some number of keys. There will, very rarely, be test failures in correct
student code, but I have never actually heard of this happening.

I'm open to suggestions for ways to test this which don't have that
vulnerability, but properly testing for randomness requires statistical
methods way beyond the scope of this exercise.

**Comment by ZapAnton** [comment]
Should the responsibility of students be tested?

If somebody does not want to understand how randomness works, they will skip the test case/exercise or hardcode 100 strings, which will be noted on the website by the mentors(with further explanations).

Or am i missing some key moment in the educational process?

**Comment by petertseng** [comment]
> Should the responsibility of students be tested?

Right, so the questoin in one direction is how thorough the tests are required to be. There may always be things that only human review can find, but if a reasonable amount of effort can be spent to find some things before a human effort needs to be expended, that can be good. I can't attempt to define how much is reasonable. There was a discussion about leap in https://github.com/exercism/problem-specifications/issues/1281 - should it only test four cases, or more? Not the same nature (no randomness) but same vein. A student could just have a lookup table with only four entries. Is that okay?

> While the probability of 2 or more generated keys being equal is extremely low, it is still a probability, on which test completion is based. That does not sound like a solid test case.

That's true, and not just in Exercism context, but in any context seeing a test fail when actually the code is fine causes much fatigue. How to deal with it?

> If the random_key is hardcoded the tests will never finish running

There could be a disadvantage if the student doesn't realise this is happening (perhaps the student innocently does this as a first implementation, just to make sure the types are correct), and the test just sits there with no feedback. Maybe some adjustment such as giving up and failing the test if too many attempts were made and we still don't have the requisite number of keys.

**Comment by coriolinus** [comment]
> How about calling the function some fixed amount of times and checking if the generated sets are of the same length and this length is equal to the amount of generated strings?

Isn't this exactly the current approach? 

> The `encode_random_uses_randomly_generated_key` test checks the randomness of generated keys, by generating 100 keys, placing them into HashSet and then checking, if the length of the set is 100.

**Comment by ZapAnton** [comment]
Perhaps a poor wording on my end.

What I propose is instead of using the `while` loop to wait until the set is full and thus accidentally causing the test suite to run forever without any feedback for the student we could add a number of times the loop should run and check the final state of generated sets(not just one set)

**Comment by coriolinus** [comment]
There's no `while` loop in [the current test](https://github.com/exercism/rust/blob/master/exercises/simple-cipher/tests/simple-cipher.rs#L142-L149):

```rust
fn encode_random_uses_randomly_generated_key() {
    let mut keys = HashSet::new();
    let trials = 100;
    for _ in 0..trials {
        keys.insert(encode_random(PLAIN_TEXT).0);
    }
    assert_eq!(keys.len(), trials);
}
```

The number of generated keys is always exactly 100 in this implementation. What would you change?

**Comment by coriolinus** [comment]
Closing this as it looks like the existing code already implements the proposed solution. @ZapAnton, please feel free to reopen if I have misunderstood you.
