### ISSUE TITLE
rna-transcription: Tests should check the value of the Err

### ISSUE THREAD

**Issue by petertseng** [exercism/rust#596]
In https://github.com/exercism/rust/pull/575 the example now returns an error and the instructions say "If string contains invalid nucleotides return index of first invalid nucleotide"

Should the tests check that the implementation does in fact designate that first invalid index?

Possible choices:

* Decide that it should, and make a PR to make it happen; that PR should close this issue by keyword
* Decide that it should not, and close this issue
* Point out that the test already does this because I missed it when writing this issue

**Comment by coriolinus** [comment]
I think that at least one test should check the value of the `Err`, to ensure the student has implemented it properly. I don't think that all tests need to.
