### ISSUE TITLE
“Macros” exercise: chance of a non-compiling code

### ISSUE THREAD

**Issue by withkittens** [exercism/rust#600]
Consider a solution from a student:

```rust
#[macro_export]
macro_rules! hashmap {
    () => {
        HashMap::new()
    };

    ($($key:expr => $value:expr),+) => {
        {
            let mut hm = HashMap::new();

            $( hm.insert($key, $value); )*

            hm
        }
    };

    ($($key:expr => $value:expr),+,) => {
        hashmap!($($key => $value),*)
    };
}
```

While it passes the tests, the code will fail to compile if `HashMap` is not imported to a scope first. ([Playground](https://play.rust-lang.org/?gist=4a8a4266752b95b8a2a3f48917953656&version=stable&mode=debug&edition=2015))

I think we need to tweak tests to teach students about such case.

Would you like me to fill a PR?

**Comment by Bert-Proesmans** [comment]
Your playground link points to irrelevant code.

Note that the playground doesn't always generate a new unique share link, for example in cases where you click the share button a second time too soon after the first time.

**Comment by coriolinus** [comment]
This has been up for a month. The playground link has not been fixed. I do not understand the thrust of the problem. I will close this issue now.

**Comment by Emerentius** [comment]
I was just wondering where this issue has gone.

Here's an updated [playground link](https://play.rust-lang.org/?gist=cabc792ebf16e75a2726f6cd01d2e969&version=stable&mode=debug&edition=2015)
The fix is easy, simply invoke the macro somewhere where the HashMap hasn't been imported.
