### ISSUE TITLE
Inappropriate use of usize

### ISSUE THREAD

**Issue by skade** [exercism/rust#601]
While going through the exercises, it occured to me that a couple of them use `usize` inappropriately. A good example is `difference_of_sums`.

```rust
pub fn difference(n: usize) -> usize {
    square_of_sum(n) - sum_of_squares(n)
}
```
`usize` is the pointer-sized integer type and should not be used for general numeric computation. Here, a fixed size of u64 is probably a good default bet. We should educate its use only when actually indexing into memory, like vec and slice (`series` is a good example here).

I have found at least one other such exercise, raindrops.

Other exercises take a different strategy, for example `nth prime` (passes u32).

**Comment by ijanos** [comment]
I agree with this. Thanks for the suggestion, would you mind opening a pull request?

**Comment by coriolinus** [comment]
From the [Rust Book](https://doc.rust-lang.org/book/second-edition/ch03-02-data-types.html#integer-types):

> So how do you know which type of integer to use? If you’re unsure, Rust’s defaults are generally good choices, and integer types default to `i32`: this type is generally the fastest, even on 64-bit systems. The primary situation in which you’d use `isize` or `usize` is when indexing some sort of collection.

A list of exercises which may be affected:

```sh
$ rg -trust '[ui]size' --files-with-matches --glob '!example.rs' | cut -d/ -f1 | sort -u
Sat Sep  1 02:31:52 DST 2018
```
- [ ] all-your-base
- [ ] binary-search
- [ ] book-store
- [ ] circular-buffer
- [ ] difference-of-squares
- [ ] dominoes
- [ ] hamming
- [ ] largest-series-product
- [ ] luhn-from
- [ ] luhn-trait
- [ ] macros
- [ ] nucleotide-count
- [ ] ocr-numbers
- [ ] parallel-letter-frequency
- [ ] raindrops
- [ ] react
- [ ] rna-transcription
- [ ] robot-simulator
- [ ] saddle-points
- [ ] series
- [ ] simple-linked-list
- [ ] spiral-matrix
