### ISSUE TITLE
accumulate: should tests enforce not mutating the input?

### ISSUE THREAD

**Issue by petertseng** [exercism/rust#628]
As can be seen in current implementation of https://github.com/exercism/rust/blob/master/exercises/accumulate/example.rs , an implementation that mutates the input is accepted. this behaviour is unlike traditional `map`. Should tests enforce that the input is not mutated?

**Comment by Emerentius** [comment]
With the current interface of passing a `Vec`, I don't see how that would be possible. The user owns it, we have no access anymore.

**Comment by petertseng** [comment]
> The user owns it, we have no access anymore.

I thought about this in the context of this rightfully-pointed out fact. I don't currently see a way to do this without changing the signature. I would like to close this in favour of https://github.com/exercism/rust/issues/629.

If anyone sees a way to achieve this, please say and at that time we can consider reopening the issue.
