### ISSUE TITLE
bracket-push: outdated "from trait" tag

### ISSUE THREAD

**Issue by Emerentius** [exercism/rust#632]
In the recent removal of the `Brackets` struct requirement in the bracket push exercise, this tag was left in, which caused confusion and more "object-oriented" solutions to be submitted.

**Comment by petertseng** [comment]
For the person who wants to fix this, this person should remove https://github.com/exercism/rust/blob/master/config.json#L608 line. This person should reference https://github.com/exercism/rust/pull/620 as the original removal
