### ISSUE TITLE
dot-dsl: testcases pass for trivial Node/Edge impls

### ISSUE THREAD

**Issue by mbillingr** [exercism/rust#640]
Testcases that test if the builder correctly adds attributes to nodes/edges use the same builder to create the expected cases.

Example:
```rust
    let nodes = vec![Node::new("a").with_attrs(&[("color", "green")])];
    let graph = Graph::new().with_nodes(&nodes);

    assert_eq!(
        graph.nodes,
        vec![Node::new("a").with_attrs(&[("color", "green")])]
    );
```

This allows students to "cheat" with trivial implementations of `Node` and `Edge`. Something like this passes all tests:

```rust
#[derive(Debug, Clone, Eq, PartialEq)]
pub struct Node;

impl Node{
    pub fn new(from: &str) -> Self {
        Node
    }

    pub fn with_attrs(mut self, attrs: &[(&str, &str)]) -> Self {
        self
    }
}
```

I don't think this is intended, is it?

**Comment by coriolinus** [comment]
You're right that this isn't intended behavior. Right now we're depending on code review to reject "solutions" like those, but a better solution might be to add a function to node like this:

```rust
pub fn get_attr<'a, 'b>(&'a self, &'b str) -> &'a str { ... }
```

Once that's in, we could just add a test that the builder was actually setting the attributes.
