### ISSUE TITLE
Replace init_exercise.py

### ISSUE THREAD

**Issue by coriolinus** [exercism/rust#641]
The exercise init script isn't great. It gets the job done for creating an exercise from scratch, but that's not actually the most common desired use case. The most common desired use case is to update an exercise's tests based on updates to the problem specifications.

Also, the thing is in python, and this is the Rust track. We have a legitimate case to RIIR here.

## Required Features

- written in Rust (stable preferred, but not required--people hacking on this repo can install nightly if necessary)
- can just update `config.json`
- can just create an exercise without touching `config.json`
- can just update an exercise without touching `config.json`
- when creating or updating an exercise: if `problem-specifications` repo is available locally, updates that repo against the current head of master. If it is not available locally, clones it. Either way, uses the current master branch of that repo to get problem specifications. 
- when updating an exercise: keeps a copy of existing `test_*_property` implementations instead of regenerating. This may be done on a purely textual basis. If these implementations do not exist, they are generated as per the "new exercise" case to ease test upgrades.
- when updating an exercise: keeps a copy of existing tests. Tests from the canonical data may be overwritten, but tests not overwritten should be retained in existing form. This helps ensure that optional tests and track-specific tests are not destroyed when updating.

**Comment by ZapAnton** [comment]
A couple of distribution questions:
- Should the Rust version of init_exercise be placed in the `bin` folder as another crate or should it have it's own repo?
- Should the new version be used via `cargo run --some --flags` / bash script or be used as a separate binary (like configlet)
- Should every new command be it's own crate?

**Comment by coriolinus** [comment]
> Should the Rust version of init_exercise be placed in the bin folder as another crate

Yes, that seems best

> Should the new version be used via `cargo run --some --flags` / bash script or be used as a separate binary (like configlet)

Well, we shouldn't be versioning a binary in git! However, cargo commands work best when the pwd is the crate root, and most of the rest of the repo commands here assume you're in the repo root. As a practical matter, it's probably easiest to write a bash script which builds a release version of the tool and then copies it into `bin/`. 

> Should every new command be it's own crate?

I think you mean, should the update and generate commands be in separate crates? That's an implementation detail which is ultimately up to the person who writes this. I don't have any strong opinion on that. If I end up writing this, I'd probably end up writing a library and a thin binary wrapper around it, both of which would live in the same crate. That's just my own preferred pattern for simple binaries, though; alternate designs are also valid.

**Comment by ZapAnton** [comment]
> when creating or updating an exercise: fetches appropriate canonical data and metadata directly from github; no need to download the problem specifications repo

Could you explain this one, please? In the current `init_exercise` script the repo is downloaded so that `configlet` could successfully run the `generate` command. If no repo is present how do you expect to use `configlet?`

**Comment by coriolinus** [comment]
Is that so? I'd forgotten. In that case, replicating the current behavior should be fine. I'll edit the requirements.

**Comment by ZapAnton** [comment]
Since we touched the `configlet` utility, could I propose another feature (or at least a discussion of a feature): 
Currently `init_exercise` tries to locate `configlet` in the `bin` folder and if there is no such file there it invokes `fetch-configlet` script. In the new utility, could we instead ask the utility itself to fetch `configlet` and possibly add a new command for fetching `configlet` to cover the task that `fetch-configlet` now does? The benefit is that `fetch-configlet` becomes cross-platform feature, available to any contributor, because the current shell script would not on Windows and possibly on some versions of the shell.

**Comment by coriolinus** [comment]
I have no objection to RIIR-ing `fetch-configlet` in Rust. It should not be
part of the `init_exercise` utility. It should be its own crate in
parallel. If it is implemented using the thick library/thin binary pattern,
it becomes easy for `init_exercise` to import some appropriate function
which will download an appropriate configlet into `bin/`.

**Comment by coriolinus** [comment]
I will start working on a `fetch-configlet` rust script.

**Comment by ZapAnton** [comment]
Two questions:
- Should only `fetch-configlet` be RIIRed or should `test-exercise`, `format_exercises` also be included?
- Why do you not want to include this commands in `init_exercise`? Potentially it could evolve in some sort of universal track manager with every needed feature included (also it _already_ not just `init_exercise` since it will work more with upgrading exercises and `config.json` not just generating them)

**Comment by coriolinus** [comment]
Two answers:

- rewrite only what we need to. I don't particularly object if
test-exercise, format_exercises are eventually RIIR'd, but they don't need
to be in order to support this objective, so we shouldn't take on work
quite yet.
- Monolithic tools aren't great. We'd do better to follow the unix
philosophy, writing many small tools each of which does exactly one thing.
That's more composeable for the future.

Agree that the scope of this tool has expanded past initializing an
exercise. Feel free to rename it to something more appropriate. Possibly if
it's structured as a CLI app with subcommands, it could simply be called
`exercise`, so one might call `exercise add linked-list`, or `exercise
update grep`, or whatever.

**Comment by ZapAnton** [comment]
If we RIIR the scripts into several separate tools, will it not hurt usability? Rust compile time currently is rather long and if potential contributor needs to compile them all they may find it quite annoying.

**Comment by coriolinus** [comment]
I'm not really concerned with the build times. Worst case, we write a
`build-tools.sh` script which takes care of building all our rust tools and
copying the binaries into the bin folder. It may take a minute or two the
first time, but after that, they're all right there. In any case, that's
out of scope for this issue.

**Comment by ZapAnton** [comment]
Got it.

Right now I have an initial version of RIIRed `init_exercise` with almost complete `generate` subcommand on my hands. I was planning to open WIP PR in the near future with it. How should I address the `fetch-configlet` situation? If you are planning to rewrite it, should I just include the invocation of the shell script, which potentially will be replaced with your implementation?

**Comment by coriolinus** [comment]
I've retracted the RIIR of the fetch-configlet script. Feel free to incorporate that code into your own tool, but I no longer think it makes sense to write as a standalone tool. The bash script was faster in all cases, if you count compile time; that made it impractical for a tool which only ever needs to be run once per environment. 

Instead of incorporating this code, it may be simpler to just accept a POSIX restriction for the exercise tool, and call `fetch-configlet` in a [`Command`](https://doc.rust-lang.org/std/process/struct.Command.html).
