### ISSUE TITLE
Should the example solutions be placed in the `examples` directory?

### ISSUE THREAD

**Issue by ZapAnton** [exercism/rust#658]
As shown in the [Cargo book](https://doc.rust-lang.org/cargo/guide/project-layout.html) an [some](https://github.com/hyperium/hyper/tree/master/examples) [popular](https://github.com/iron/iron/tree/master/examples) projects it is typical to place example files in the `examples` directory.

Should this track follow the same convention?

Bonus point: `cargo fmt` command would automatically format files in the `examples` directory, so the [format script](https://github.com/exercism/rust/blob/master/bin/format_exercises) could be simplified

**Comment by petertseng** [comment]
To help make this decision, the people making this decision should look at https://doc.rust-lang.org/cargo/reference/manifest.html#examples that explains how Cargo treats `example`s.

Caution is advised, as the examples used by Exercism are *not* "example uses of the functionality provided by the library" (they are the implementation of the library!).

**Comment by ZapAnton** [comment]
> Caution is advised, as the examples used by Exercism are not "example uses of the functionality provided by the library" (they are the implementation of the library!).

I think in case of Exercism the line between the library and it's functionality is quite thin (what is functionality of the exercise: the methods which pass the tests or the process of implementing this methods?).

Also a possible point in favor for the `examples` folder: To teach students, who refer to this repo for whatever reason, a typical project layout in Rust

**Comment by petertseng** [comment]
Notice how the example solution of scale-generator in https://github.com/exercism/rust/pull/667 could have stood to be separated into multiple files. That's not currently possible with just `example.rs`, but may potentially be made better with placing examples in a directory (though this suggestion is not specific to any particular directory)

**Comment by workingjubilee** [comment]
This issue is directly relevant to v3's track structure. I think I'm going to bring it up there.

**Comment by coriolinus** [comment]
v3 specifies an example file which is not the `examples` directory. I don't see that changing at this point, so I'm closing this now.
