### ISSUE TITLE
check-exercises: Target only modified exercises?

### ISSUE THREAD

**Issue by ZapAnton** [exercism/rust#674]
I seems not very optimal to re-compile every existing exercise just to check changes in one exercise.

Should the `check-exercises.sh` script target only those exercises, that where modified in the PR, and target all the exercises only on the  weekly Travis launches on the `master` branch?

This should make the checks and usefull feedback to appear faster

**Comment by coriolinus** [comment]
That sounds like a useful improvement to me.
