### ISSUE TITLE
exercise util should use the same template 

### ISSUE THREAD

**Issue by coriolinus** [exercism/rust#679]
When using `exercise generate`, the generated file is different depending on whether or not canonical data exists for that exercise:

- if an exercise has canonical data, the tests module has a nice explanatory doccomment
- if an exercise does not have canonical data, the tests module does not have the module doccomment 

Both cases should use the same basic template, with the doccomment.

**Comment by dvermd** [comment]
I have a PR for this one.
There seems to be some redundancy in the template as in `[utility][utility]` and `[canonical data][canonical data]`.
Should I had another commit to dedup these ?
