### ISSUE TITLE
exercise util: generate more useful process_X_case defaults

### ISSUE THREAD

**Issue by coriolinus** [exercism/rust#683]
When generating `process_X_case` functions, the current implementation causes the compiler to complain about unused variables. We should, instead of generating comments describing what it might look like, just generate the example directly. I.e. using the `abbreviate` case:

```rust
fn process_abbreviate_case<I, O>(input: I, expected: O) {
    assert_eq!(
        student_abbreviate_func(input), // TODO: what is the actual name of student_abbreviate_func?
        expected
    );
}
```

**Comment by senekor** [comment]
exercise util has been deleted since, see [this thread](https://github.com/exercism/rust/pull/1722#issuecomment-1712950187) for more context.
