### ISSUE TITLE
exercise util: document input type for process_X_case

### ISSUE THREAD

**Issue by coriolinus** [exercism/rust#684]
When generating `process_X_case functions`, we should generate documentation for the implementer about the expected input items. 

This feature is not very useful useful right now, because it will tend to generate comments like

```rust
// expected input format: (input, )
```

As such, this issue should probably wait until https://github.com/exercism/rust/issues/681 is resolved. 

However, once we implement input struct unpacking, it should say:

```rust
// expected input format: (phrase, )
```

And once we implement unpacking single-item tuples, it should say:

```rust
// expected input format: phrase
```

**Comment by senekor** [comment]
exercise util has been deleted since, see [this thread](https://github.com/exercism/rust/pull/1722#issuecomment-1712950187) for more context.
