### ISSUE TITLE
exercise util: fix update cmd test file layout

### ISSUE THREAD

**Issue by coriolinus** [exercism/rust#686]
The test file is easiest for a human to read and understand if it contains the following sections in sequence:

- test module doccomment
- imports
- `process_X_case` implementations
- tests

The `exercise update` command should ensure that the test output file conforms to that sequencing. 

From the exercise tool's point of view, https://github.com/exercism/rust/issues/685 requires parsing the test file to determine which tests exist, and what bytes they contain, anyway. Given that information, it should not be difficult to insert new `process_X_case` implementations at the end of the appropriate section.

**Comment by senekor** [comment]
exercise util has been deleted since, see [this thread](https://github.com/exercism/rust/pull/1722#issuecomment-1712950187) for more context.
