### ISSUE TITLE
exercise util: use templates instead of manually modifying files

### ISSUE THREAD

**Issue by coriolinus** [exercism/rust#698]
Currently many operations in this utility operate at the file level, directly appending strings and bytes. We'll get better results with higher-level abstractions: never directly appending to `Config.toml`, for example, but using a toml-parsing crate instead. Likewise, writing the tests file will be much easier using a template system like [`handlebars`](https://github.com/sunng87/handlebars-rust). Note that this mention of handlebars isn't a requirement to use that particular crate, just an example of a plausible templating engine.

It is not necessary to implement this before #679 or #686, but those issues will probably be easier to fix after the fix for this has been implemented.

**Comment by ZapAnton** [comment]
If by `Config.toml` you mean `Cargo.toml`, then it is already parsed with the `toml` crate and there is no appending: the content of the file is parsed, modified and then the new content fully overrides the old one. What should be added to this behavior in the contest of this issue?

**Comment by coriolinus** [comment]
See the changes [here](https://github.com/exercism/rust/pull/700/files/e943a25c7a26449e08f1205c2a68cd34f7f279da..09d02059f81863a210f47bc0afddcde5eaa7d38d#diff-492f508c9336f1c9eaa25bf9ac159c15). There are some other changes in that diff, mostly due to some necessary macro refactoring, but that file has the most important ones.

**Comment by senekor** [comment]
exercise util has been deleted since, see [this thread](https://github.com/exercism/rust/pull/1722#issuecomment-1712950187) for more context.
