### ISSUE TITLE
check-exercises: When looking for the modified exercises, the script sould detect the exercise directory, not the modified files

### ISSUE THREAD

**Issue by ZapAnton** [exercism/rust#714]
The current check for the modified exercises in the `_test/check-exercises.sh` script (`git diff --name-only master | grep "exercises/" | cut -d '/' -f -2 | awk -v repo=$repo '{print repo"/"$1}'`) locates all modified files paths, cuts the paths so that only path to exercise directory remains, and proceeds to check the exercises from the located paths.

The problem is that, when there are several modified files in the exercise directory, for instance `Cargo.toml`, `example.rs` and `src/lib.rs`, the command return all of their paths, which are identical:

```text
/exercises/pythagorean-triplet
/exercises/pythagorean-triplet
/exercises/pythagorean-triplet
```

The command should instead return a single `/exercises/pythagorean-triplet` path

**Comment by coriolinus** [comment]
After cut, before awk: sort -u
