### ISSUE TITLE
exercise util: Make the val_as! macro accept null as valid input

### ISSUE THREAD

**Issue by ZapAnton** [exercism/rust#719]
Discovered the issue when tried to use the configure subcommand on the `pythagorean-triplet` exercise.

The `unlocked_by` field is set to `null` in the `config.json`, which makes this line to return error:

```rust
get!(existing_config, "unlocked_by", as_str)
```
The error is returned, because `as_str` cannot parse `null` and instead invokes the `.ok_or_else` function.

Also the error message could be better, when `val_as!` is called from `get!`. The current message is not very helpful:
```text
Error: SchemaTypeError { file: "config.json", field: "$ name", as_type: "str" }
```

**Comment by coriolinus** [comment]
Seems like `val_as` is doing the right thing, here; the calling code should
be doing something like

match get!(existing_config, "unlocked_by") {
    Value::Null => unimplemented!(),
    Value::String(s) => unimplemented!(),
    _ => unimplemented!(),
}

**Comment by ZapAnton** [comment]
Just to make sure: val_as is supposed to be used, when we deffinetly know the type of the Value, correct?

**Comment by coriolinus** [comment]
Yes, it's meant to be used where there should be an infallible conversion.
One could imagine writing a maybe_val_as! macro which returned Option<type>
and handled null inputs gracefully, but I haven't needed to write that
macro yet.
