### ISSUE TITLE
Luhn with the test 'simple_valid_sin'  in the main track

### ISSUE THREAD

**Issue by sepiropht** [exercism/rust#744]
Only one single test doesn't pass with my code. 
it 's simple_valid_sin, it supposed to be true . But how can this be possible, maybe an error in test case ? ``(5 + (9 * 2 - 9)) % 10 != 0`` this give me false.  What do i 'm missing ?

**Comment by petertseng** [comment]
Need to double every second digit starting from the right.

For `59`, that's 5, not 9.

`((5 * 2 - 9) + 9) % 10 == 0`

**Comment by sepiropht** [comment]
That weird, my code pass all test except this one. I didn't see **FROM RIGHT**.
Thanks for the speed answer
