### ISSUE TITLE
Improving the track structure

### ISSUE THREAD

**Issue by iHiD** [exercism/rust#766]
Hello @exercism/rust 

Rust is one of two tracks (Rust/Python) that we're really struggling with from a mentoring point of view. After reviewing the config.json of both tracks, we have highlighted that both have a very difficult and fast learning-curve for the students. This makes the exercises much harder to mentor as the mentor has to cover many topics per exercise, which is very overwhelming.

We have spent the last three months developing a framework to design track structures. We have implemented it in Ruby, and are working on implementing it in CSharp. We would like to try implementing it in Rust too to try and solve the problems we are seeing. Achieving this will involve one maintainer working with @F3PiX and the Exercism core team, going through the framework and restructuring things. It will take approximate 1-2hrs per week for 4 weeks for us to get the Rust track to where we want it to be.

I'm not sure if there is a primary Rust maintainer or a specific maintainer who would like to take on this role, but if you could nominate one person who would be willing to help, we'll get the process going on Slack :) I'm guessing from recent commits that the most likely candidates would be @coriolinus, @petertseng or @ZapAnton.

Thank you! 💙

**Comment by coriolinus** [comment]
[That's a good idea](https://github.com/exercism/rust/pull/560#issuecomment-400138725)!

**Comment by kytrinyx** [comment]
Closing in favor of https://github.com/exercism/rust/issues/809
