### ISSUE TITLE
word-count: Problem statement could use a couple of more examples

### ISSUE THREAD

**Issue by atil** [exercism/rust#788]
First glance at the problem statement might might lead to an assumption that the only delimiter is the whitespace, as it is the only example. Maybe one or two more examples from the test cases with different delimiters. This one, for instance:

```text:
car : carpet as java : javascript!!&@$%^&

car: 1,
carpet: 1,
as: 1,
java: 1,
javascript: 1
```

**Comment by gabriel376** [comment]
I can work on this.
However, if we decide to change, we should change the [Problem Specification](https://github.com/exercism/problem-specifications/blob/master/exercises/word-count/description.md) and update all tracks, not only Rust.

**Comment by coriolinus** [comment]
Agree. Would you rather push the issue up to that repo, or test-drive the
work in this track first?

**Comment by gabriel376** [comment]
I will open an issue on [Problem Specification repo](https://github.com/exercism/problem-specifications)

**Comment by gabriel376** [comment]
I opened exercism/problem-specifications#1461
I suggest to close this one

**Comment by coriolinus** [comment]
Closed pending the result of https://github.com/exercism/problem-specifications/issues/1461
