### ISSUE TITLE
saddle-points: Reconcile 1-based indices in README with 0-based indices in tests

### ISSUE THREAD

**Issue by petertseng** [exercism/rust#791]
https://github.com/exercism/problem-specifications/pull/1429 which was applied to this track in https://github.com/exercism/rust/pull/789 uses one-based indices in the https://github.com/exercism/rust/blob/master/exercises/saddle-points/README.md. The track still uses zero-based indices in the https://github.com/exercism/rust/tree/master/exercises/saddle-points/tests . This inconsistency is a potential source of student confusion.

Various solutions:

1. Change the tests to be one-indexed.
2. Maintain our own README with zero-based indices. You do this by placing the README we want in `.meta/description.md`. Not recommended.
    * We cannot just use hints.md since that only allows additive changes. This is a modification of existing text, which hints.md does not support.
3. Keep both the README and tests as is, but insert a statement somewhere telling students to be aware of the discrepancy.
4. Suggest to problem-specifications that no, really, they should go back to using zero-based indices.
5. Your suggestion here.

I do not recommend 2 (maintain our own README) so if you want to go this route you have to convince me why we should be in the business of maintaining our own READMEs.

I have no specific preferences or recommendations between any of the other options.

**Comment by petertseng** [comment]
EBWODP

> problems

too vague. try instead "student confusion"

**Comment by petertseng** [comment]
> Change the tests to be one-indexed.

Compare with existing matrix libraries in Rust.

https://docs.rs/matrix/0.22.0/matrix/#example
https://www.nalgebra.org/rustdoc/nalgebra/base/struct.Matrix.html#two-dimensional-indices
https://docs.rs/simple-matrix/0.1.2/simple_matrix/struct.Matrix.html#examples-4

These all imply zero-based indexing.

The Rust track is under no *obligation* to use zero-based indexing solely because of the presence of libraries that do so, but it is a factor to be considered.

**Comment by TheDarkula** [comment]
My recommendation is to be consistent with the language and use zero as the first index.

**Comment by coriolinus** [comment]
I think that the short-term solution is 3: this sort of thing works well with the `.meta/hints.md` insertion; it's not a hint, but we can adjust the header to whatever works best. 

Long term, once the `exercise` tool can reliably regenerate tests from the canonical data without clobbering too much, we should probably do solution 1.

**Comment by petertseng** [comment]
> Long term, once the `exercise` tool can reliably regenerate tests from the canonical data without clobbering too much

When that day comes, there will possibly be some translation layer necessary to represent a given JSON value as a Rust value. If there still remains a desire to use zero-based indexing at that time, it would be possible to do so at that translation layer.

I acknowledge that what I have just said has no bearing on what course of action is chosen presently, so the main purpose of saying it was to prepare the idea for the time when it may be necessary.
