### ISSUE TITLE
Notification Of Track Changes To Students And Mentors

### ISSUE THREAD

**Issue by TheDarkula** [exercism/rust#813]
With the ongoing changes to the Rust track, we need a way to notify students and mentors that the track is being reworked. This could be an email, exercism dashboard icon, etc. It would be good to include a link to the latest merged changes so they can read the documentation for the change as well.

**Comment by workingjubilee** [comment]
Has there been any progress on this, or are there any blockers to take care of?

**Comment by iHiD** [comment]
No. TheDarkula gave up on trying to rework the track due to lack of time and general frustration :) But this is now sort of irrelevant as v3 reworks everything.

**Comment by workingjubilee** [comment]
Understandable. Is there a (nascent) plan for messaging to students around v3 that would replace a more specific plan for in-track messaging? I haven't really seen any rumblings across the website itself.

**Comment by iHiD** [comment]
There will be, yes. Once we have enough Concept Exercise Issues written by maintainers, I will start raising the profile/awareness of what we're doing to students, and ask them to help implement those exercises.

**Comment by nertpinx** [comment]
Not sure if v3 handles that as well, but it would be nice to also get notified for things like updated exercises (e.g. added new test cases) so that I don't have to go through old ones one by one.

Also shouldn't this be an issue in one of the core repositories as it relates to the whole site and not just this track?

**Comment by coriolinus** [comment]
The track anatomy project has been superseded by v3.
