### ISSUE TITLE
Hamming exercise doesn't cover topic `result`

### ISSUE THREAD

**Issue by Stigjb** [exercism/rust#825]
https://github.com/exercism/rust/blob/88d26a54a737036f32c12e370d252a4f1cd42d59/config.json#L498-L506

In the list of side exercises, Hamming is listed as covering the topic `result`. There is nothing in the specification or test that suggests using Result types, but the hamming function returns an Option type.
I suggest changing the config to list the `option` topic instead.

**Comment by coriolinus** [comment]
1. Thank you for direct-linking to the relevant section! It makes things much easier for me.
2. Good spot! You are exactly right. Apparently it's been like that for almost a year now, since 5638873396d9ed0522d8117e2840d380b9305036.

Are you willing to open a PR changing "result" to "option" there?

**Comment by Stigjb** [comment]
I opened a PR, however I have also noticed this issue: #529 . Is the intention still to standardize the topics? In the [list of topics](https://github.com/exercism/problem-specifications/blob/master/TOPICS.txt) in problem-specifications, there is an entry called "optional_values".

**Comment by coriolinus** [comment]
I believe `optional_values` per #529 is referring more to variadic functions than monadic return values. `option` seems like the better usage, here, to me.
