### ISSUE TITLE
Simple Linked List and encouraging users to write idiomatic Rust

### ISSUE THREAD

**Issue by timvermeulen** [exercism/rust#826]
Most exercises of the Rust track are good at teaching users about Rust's best practices (a perk of having a language specific track 😄), but I think Simple Linked List is lacking a bit in this regard.

- One of the tasks is to implement `fn rev(&self) -> SimpleLinkedList<T>` where `T: Clone`, and this signature has several downsides. One limitation is that lists of some `T` that isn’t `Clone` can’t be reversed, even though there's nothing about the concept of reversing a linked list that requires cloning the elements. And even if `T` does implement `Clone`, `rev` clones all elements without that being obvious to the caller. Rust makes a big deal out of not hiding implicit copies or allocations, so I think this is a pretty big downside.
Giving the `rev` function ownership of `self` and leaving out the `T: Clone` bound solves both of these problems. Users of this type can then still reverse a list they only have a reference to by explicitly cloning that list and then reversing it. And users that already have an owned list can then reverse it without paying the performance penalty of unnecessary clones.
- Another task is to implement the `From<&'a [T]>` trait where again `T: Clone`. Here, implementing the `FromIterator<T>` trait would be more idiomatic for many of the reasons listed above. `FromIterator` would also allow for e.g. `Vec<T>` to be turned into a list (without any clones), not to mention any other data structure or iterator.
- The last task is to implement the `Into<Vec<T>>` trait. Implementing the `IntoIterator` trait would be more flexible here, because the user may want another data structure. `IntoIterator` would also save allocating the vector in case they just want to iterate it once.

Thoughts?

**Comment by coriolinus** [comment]
Thank you for the thoughtful comment!

- WRT the `Clone` bound, there are actually three options:
    - bound the list on `T: Clone`
    - change the signature to consume `self` as you suggest
    - neither, just complexify the required implementation. The simplest solution I can think of which doesn't require consuming `self` or bounding on `Clone` involves making each node hold an `Rc<T>`, which can then be cloned to create the new list. That gets tricky with the lifetimes, though, I think. I haven't tried writing it.

    For production code, we'd pick option 3. Here, we picked option 1 because it was simple to understand and to implement. I'm not opposed to switching to option 2, as you suggest.
- WRT `FromIterator` vs `From<&'a [T]>`: That's a good idea.
- WRT `IntoIterator`: my instinct is that implementing `Into<Vec<T>>` is substantially simpler than implementing `IntoIterator` for a linked list, but I could be wrong. For this exercise, I'd weight things heavily toward ease of implementation, even at the cost of some idiomaticity. 

I'd be happy to review a PR implementing the suggested changes. Are you willing to implement such a PR?
