### ISSUE TITLE
simple-linked-list: test_peek_returns_head_element doesn't actually test what it claims to

### ISSUE THREAD

**Issue by leibnitz27** [exercism/rust#834]
The `peek` of simple linked list is defined to return head.

However, it will also work if the user has created a stack, and peek returns the *last* element.
(In general, simple linked list's definition is a little confusing - pop and peek typically return the same element, but pop here is defined to return tail, and peek to peek at head).

This test should test with 2 different elements, or a new test should be added.

https://github.com/exercism/rust/blob/da21df6e8c8f7406ebe0c4ae2b68631b84fa27b1/exercises/simple-linked-list/tests/simple-linked-list.rs#L42-L50

**Comment by coriolinus** [comment]
Huh, interesting. I see what you mean; it looks like someone left out a line from that test. It would work better like this, right?

```rust
#[test]
#[ignore]
fn test_peek_returns_head_element() {
    let mut list: SimpleLinkedList<u32> = SimpleLinkedList::new();
    assert_eq!(list.peek(), None, "No element should be contained in list");
    list.push(2);
    assert_eq!(list.peek(), Some(&2), "Element must be 2");
    list.push(3);
    assert_eq!(list.peek(), Some(&2), "Element must be still 2");
}
```

@leibnitz27 would you like to make a PR with that fix?

**Comment by ocstl** [comment]
From the problem description: 

> This variant of linked lists is often used to represent sequences or push-down stacks (also called a LIFO stack; Last In, First Out).

From my understanding, `peek` and `pop` both return the head element, except that `peek` doesn't remove it. Thus, I believe this test makes sure that the implementation doesn't remove the head element. That being said, as @leibnitz27 pointed out, it doesn't check whether `peek` returns the head or tail element.

This version of the test seems to cover all the bases:
```
#[test]
#[ignore]
fn test_peek_returns_head_element() {
    let mut list: SimpleLinkedList<u32> = SimpleLinkedList::new();
    assert_eq!(list.peek(), None, "No element should be contained in list");
    list.push(2);
    assert_eq!(list.peek(), Some(&2), "Element must be 2");
    assert_eq!(list.peek(), Some(&2), "Element must still be 2");
    list.push(3);
    assert_eq!(list.peek(), Some(&3), "Element must be 3");
}
```

Although one could split it in two:
1. `peek` doesn't remove the head;
2. `peek` returns the new head element.
