### ISSUE TITLE
rail-fence-cipher wide character encode test is broken

### ISSUE THREAD

**Issue by BartMassey** [exercism/rust#842]
In the `rail-fence-cipher` exercise, the result string for the wide character encoding test `test_encode_wide_characters()` has spaces in it: the spaces were not filtered out before encoding. I believe that the correct answer is `"古びの池飛込水音蛙む"`.

**Comment by petertseng** [comment]
for better or worse, the space is not treated any differently from any other character, which is consistent with the fact that all other input strings do not have spaces

but not consistent with the fact that https://github.com/exercism/problem-specifications/blob/master/exercises/rail-fence-cipher/description.md originally presented a string with spaces but removed them when writing the message into the rails

as we see in https://en.wikipedia.org/wiki/Haiku#Examples or https://www.tofugu.com/japan/haiku/ there does not seem to be an objection to writing the entire haiku on one line without spaces, so we would not be breaking rules if we removed them from https://github.com/exercism/rust/blob/master/exercises/rail-fence-cipher/tests/rail-fence-cipher.rs

**Comment by petertseng** [comment]
so that is a possible solution

**Comment by BartMassey** [comment]
@petertseng That solution is fine with me. I think given the example it's reasonable for our solution to filter spaces, but this way we can be agnostic about it.
