### ISSUE TITLE
anagram skeleton missing lifetime annotation

### ISSUE THREAD

**Issue by BartMassey** [exercism/rust#843]
The skeleton for the `anagram` problem is missing a lifetime requirement. It should be

```rust
pub fn anagrams_for<'a>(
    word: &str,
    possible_anagrams: &[&'a str],
    ) -> HashSet<&'a str>
{
```

but the second `'a` is currently missing.

This may be on purpose: see issue #166, which I think is pretty dead at this point. The given signature does require lifetimes now, but they are (mostly) provided.

**Comment by coriolinus** [comment]
The stub compiles:

```sh
coriolinus@brute /mnt/c/Users/coriolinus/Documents/Projects/exercism/xrust/exercises/anagram
$ git status && git rev-parse --short HEAD && cargo check
Mon Jul 22 20:55:01 DST 2019
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
ee9ba77
    Finished dev [unoptimized + debuginfo] target(s) in 0.01s
```

IMO this is not an issue: the stub provided is sufficient to provide the student with the expected signatures. They have to inject the required lifetime annotation themselves, which is a feature, not a bug: students need to learn to work with the compiler and annotate lifetimes at some point, and this feels like an appropriate place for them to begin learning that skill. 

I am willing to hear arguments against this position, but my inclination as of now would be to close this issue without changing the stub.

**Comment by BartMassey** [comment]
If the intent is to provide this stub, a note should be added to the description indicating that the student may have to edit the stub in ways not commented in the stub. This is not a normal step in Exercism problems, since editing the stub in unspecified ways usually makes the tests fail.

**Comment by coriolinus** [comment]
The student must always edit the stub in whatever way is required to make the tests pass. 

The point of the stub is not to be a complete signature. It is to be the minimal signature which compiles. The intent is that the students can download an exercise, run `cargo test`, and immediately see pretty output with a single, failing case. Before we made it track policy to include a stub for every exercise, students needed to wade through dense miscompilation notices and inspect the test files in detail to figure out the necessary signatures, which didn't help their learning. 

> the student may have to edit the stub in ways not commented in the stub. This is not a normal step

I disagree: there are several exercises whose stubs don't compile by default:

```sh
$ fd -uu ALLOWED_TO_NOT_COMPILE
Tue Jul 23 12:38:06 DST 2019
exercises/accumulate/.meta/ALLOWED_TO_NOT_COMPILE
exercises/clock/.meta/ALLOWED_TO_NOT_COMPILE
exercises/decimal/.meta/ALLOWED_TO_NOT_COMPILE
exercises/dot-dsl/.meta/ALLOWED_TO_NOT_COMPILE
exercises/luhn-from/.meta/ALLOWED_TO_NOT_COMPILE
exercises/luhn-trait/.meta/ALLOWED_TO_NOT_COMPILE
exercises/macros/.meta/ALLOWED_TO_NOT_COMPILE
```

It is possible to inspect each of their stubs with the command

```sh
$ fd -uu ALLOWED_TO_NOT_COMPILE -x dirname | xargs dirname | sed 's|$|/src/lib.rs|' | xargs bat
```

Of those, `accumulate` has an explicit notation that the student is required to figure out the type to use, `decimal` has a comment saying "implement your type here", and the rest rely on the student to do the right thing.

If we allow exercises for which the stub doesn't even compile, with no additional notes, in 5 of 93 exercises, then I think it is not unreasonable to require the student to adjust the lifetime annotation in this case.

**Comment by BartMassey** [comment]
Fair enough. Won't trouble you further. Thanks much for your time!

**Comment by c-dante** [comment]
Hey just chiming in here -- I know it's closed and everything, but as a student going through this problem I assumed I had to try and figure out a way in rust to return a lifetime that wasn't in the input args.

On one hand it sent me down a rabbit hole of trying to figure out how to do that, "Because that's what the signature was asking of me".

It'd be great if there was an indication of the problem that massaging interfaces was allowed, because I essentially had to find bug reports and source like this to understand that it was a valid step to change.

My two cents on this, since it was SUPER discouraging as someone getting back into rust to spiral out into "I understand this stuff and what they're asking seems impossible..."

So. Yeah. Pretty valid to add a note or indication if "the code compiles" but "the signature is impossible"
