### ISSUE TITLE
exercise_readme: all tests handling

### ISSUE THREAD

**Issue by ocstl** [exercism/rust#866]
One of the students I mentored was left confused when `cargo test` failed but `cargo test -- --ignored` didn't. I believe some of the confusion may stem from this part of the README:

> If you wish to run all tests without editing the tests source file, use:
> 
> ```bash
> $ cargo test -- --ignored
> ```

Which I believe should be "If you wish to run all **ignored** tests", since those tests without the `ignore` attribute will not be run.

There is a `--include-ignored` flag available to run all tests, but it is only accepted on the nightly compiler.

**Comment by coriolinus** [comment]
Agree. This can most easily be fixed by updating the [readme template](https://github.com/exercism/rust/blob/master/config/exercise_readme.go.tmpl), and then regenerating all exercise READMEs with `bin/configlet generate .`.

**Comment by rofrol** [comment]
Thanks @coriolinus . All steps required:

```bash
git clone https://github.com/exercism/rust
git clone https://github.com/exercism/problem-specifications
cd rust
bin/fetch-configlet
bin/configlet generate .
```
