### ISSUE TITLE
Paasio exercise is lacking in... explanation

### ISSUE THREAD

**Issue by felix91gr** [exercism/rust#869]
Hi all.

I'm currently trying to figure out what is it that I'm supposed to do with the **Paasio** exercise. The description goes as follows:

> Create a wrapper for network connections and files that can report IO statistics. The wrapper must report:
> - The total number of bytes read/written.
> - The total number of read/write operations.

And here's an extra bit:

> Network and file operations are implemented in terms of the `io::Read` and `io::Write` traits. It will therefore be necessary to implement those traits for your types.

But I still have no idea what am I supposed to do. I read the provided `src/lib.rs` and `tests/paasio.rs` files and I can't figure it out.

Anything is appreciated :)

**Comment by coriolinus** [comment]
Your next step is to read about the `io::Read` and `io::Write` traits. 

Your objective is to write a wrapper struct for each of these: it contains an inner type implementing `Read` or `Write`, and also implements that trait itself. The implementation should just pass through all the actual IO operations to the wrapped struct, while collecting statistics about them. 

I will close this now, as this has no action item to change in the track. However, if you have further questions, feel free to continue responding to this issue.
