### ISSUE TITLE
Recruiting additional maintainers for Rust

### ISSUE THREAD

**Issue by kytrinyx** [exercism/rust#913]
We're about to start a big push towards version 3 (v3) of Exercism. This is going to be a really exciting step forward for Exercism, with in-browser coding, new Concept Exercises with automated feedback, improved mentoring and much more.

This to be a big community effort, with the work spread out among hundreds of volunteers across Exercism. One key thing is going to be each track having enough maintainers who have the time to manage that community effort. We are therefore putting out a call for new maintainers to bolster our numbers. We're hoping that our existing maintainers will be able to act as mentors to the newer maintainers we add, and take on a parental role in the tracks.

If you are an existing maintainer, could you please reply to this letting us know that you think you'll have time (2-3hrs/week) to help with this over the next 6 months. If you won't have that time, but still want to be a maintainer and just help where you can instead, please tell us that too. If you have come to the end of the road as a maintainer, then we totally understand that and appreciate all your effort, so just let us know.

For anyone new who's interested in becoming a maintainer, thanks for your interest! Being an Exercism maintainer is also a great opportunity to work with some other smart people, learn more about your language of choice, and gain useful skills and experience that are useful for growing your career in the technical leadership direction. Please write a comment below introducing yourself along with your Exercism handle, and telling us why you're interested in becoming a maintainer, and any relevant experience. We will then evaluate every application and contact you using your exercism email address once we have finished the evaluation process.

Thank you!

See also https://github.com/exercism/exercism/issues/5161

**Comment by houbslala** [comment]
I discovered exercism few days ago and I think this is such a great place to learn a new language! I started learning rust and I really like it.
I come from c++/c and python. I am just starting learning rust and I'd really like to help maintain the rust track.
I think my vision as beginner doing the rust track can help more advanced maintainers to make even better exercises. I can help 2-3hrs/week without any problem.

**Comment by lewisclement** [comment]
Hi,

I'm @lewisclement, mentor on the Rust track. So far I'm enjoying mentoring, and would like to invest a little bit in the design process too. Both the experience and the intrinsic (fun) aspect motivate me to do so.

So far I haven't got any professional experience with Rust. I do have some with C#, PHP and JavaScript, and during last decade I've also occasionally used C++ and Haskell.

2/3 (spread) hours is a reasonable investment for me.

**Comment by petertseng** [comment]
Existing maintainer who is unsure of consistently having 2-3 hours. I will help out where I can.

**Comment by coriolinus** [comment]
Likewise, I'm an existing maintainer who'll help where possible, but can't
commit to 3 hours weekly.

**Comment by filalex77** [comment]
Hello! I'm `BrightOne` on Exercism. I'm a (semi-active) mentor in Rust (also in Elixir and Ruby), and I'm very enthusiastic about Rust. Already proposed myself for maintaining the Elixir track, but I think I can find the extra 2-3 hours for this track.

**Comment by TheDarkula** [comment]
I am an existing maintainer and can help where I can, but I am not sure that I can commit 2-3 hours every week at this point :)

**Comment by efx** [comment]
Hi folks!
I can commit to 2/3 hours a week.
I go by efx in exercism as well and have mentored for the past 6 months and participated in the Rust track for about a year.

I'm interested in becoming a maintainer to further gain more practical Rust experience whilst helping build a free and open learning resource. Exercism galvanized my Rust interest and I'm quite grateful. [rust-rosetta](https://github.com/rust-rosetta/rust-rosetta) has been fun but I cannot justify time there while the v3 party commences. FOSSMO y'all. I'm active in a number of open source projects and communities and lead software design and development alongside colleauges @Innovu.

**Comment by workingjubilee** [comment]
I will continue to help and/or be a nuisance (be a helpful nuisance?) in whatever capacity I can. My engagements with life in general are often a bit "bursty" so I might commit 104+ hours over the next year but I sincerely doubt it will be evenly spread over 2 hours per week.

**Comment by iHiD** [comment]
@workingjubilee Great, thanks! I think you're already set up? But message me on Slack if you need any help :)

**Comment by efx** [comment]
@workingjubilee  you are not a nuisance! I've appreciated the contribution so far and know it will be helpful to us achieving v3.

**Comment by efx** [comment]
If you would like to contribute I and other maintainers would appreciate your work! But I don't know the best way to onboard new maintainers at the moment.  SO prefer to close this instead of mislead potential new contributors.
If you would like to get involved, you can certainly open a draft PR here to get existing maintainers attention or reach out to @iHiD. Thanks!

**Comment by iHiD** [comment]
Thanks @efx! 

For anyone reading this, emailing erik@exercism.io is the best way for now! 🙂
