### ISSUE TITLE
bob: update to v1.6.0

### ISSUE THREAD

**Issue by coriolinus** [exercism/rust#922]
Per https://github.com/exercism/problem-specifications/pull/1632, the bob exercise is updated to avoid some cultural sensitivity issues. I'd like this to get a relatively high priority for that reason; we don't want to offend those we don't have to.

@lewisclement, @filalex77, are either of you willing to take charge of this one? It feels like a good opportunity to get familiar with the [`util/exercise` tool](https://github.com/exercism/rust/tree/master/util/exercise). 

Procedurally, I think it's helpful if we use the Assignees section in the upper right to take ownership of an issue. I don't intend to ever assign someone other than myself to an issue or PR, and hope you guys have the same intention.

**Comment by lewisclement** [comment]
Hmmm, still getting the hang of it. Seems like the tool appends the test file. Lemme fix that.
