### ISSUE TITLE
Excercise 'Circular Buffer' doesn't actually verify that clear() clears the buffer

### ISSUE THREAD

**Issue by alexschrod** [exercism/rust#930]
I realize that this is just an academic exercise, and so leaving in such a potential memory and resource leak isn't a big deal, but I think there should still be a simple check to see that the buffer actually gets cleared, otherwise, whatever your `T` is can potentially sit inside the "cleared" buffer and waste memory and occupy other resources for a long time.

Currently, you can pass all tests with an implementation that simply sets however you keep track of your buffer's count/size to 0, while leaving the actual elements still alive within the buffer. To defend against this (IMO invalid) approach, I designed this test case:

```rust
#[test]
fn clear_actually_frees_up_its_elements() {
    let mut buffer = CircularBuffer::new(1);
    let element = Rc::new(());
    assert!(buffer.write(Rc::clone(&element)).is_ok());
    assert_eq!(Rc::strong_count(&element), 2);
    buffer.clear();
    assert_eq!(Rc::strong_count(&element), 1);
}
```
It uses `Rc` to make sure that after a `clear()`, the clone count is reduced, meaning that Rust called `drop()` on it, i.e. it was properly cleared out.

**Comment by coriolinus** [comment]
That's really good! Are you willing to open a PR adding that test to the suite?

**Comment by alexschrod** [comment]
@coriolinus Sure, I'll see what I can do. 😊
