### ISSUE TITLE
dot-dsl could use better instructions

### ISSUE THREAD

**Issue by jessechounard** [exercism/rust#943]
I apologize if this isn't the correct way to leave feedback.

I've been working through the Rust track in practice mode, and trying not to look at the tests at all before writing my code, because I don't want to just solve the tests, but write correct code that could pass any test.

Unfortunately dot-dsl requires a pretty specific module and method layout that isn't described at all in the instructions. The only way to complete the problem was to walk through the tests. I looked that the next problem (Simple Linked Lists) and it seems to include the required struct layout. Is that something that could be added to dot-dsl?

**Comment by coriolinus** [comment]
This is absolutely the correct way to leave feedback!

`dot-dsl` is one of a few exercises with the `ALLOWED_TO_NOT_COMPILE` [meta tag](https://github.com/exercism/rust/tree/master/exercises/dot-dsl/.meta). The intent in its design is meant to accomplish two goals simultaneously:

- teach the student how to declare submodules
- teach the student how to figure out how code should look by inspecting both compiler errors and the calling code, in this case, the tests

I would be receptive to a PR which improved the documentation without compromising either of those goals. The simplest way to do that would be to edit `.meta/hints.md`, then regenerate the README.

**Comment by jessechounard** [comment]
If that's the goal, I think everything is fine. Thanks for responding!
