### ISSUE TITLE
Inconsistency in DOT DSL exercise

### ISSUE THREAD

**Issue by iurii-kyrylenko** [exercism/rust#954]
Consider a specification [test_graph_with_one_edge](https://github.com/exercism/rust/blob/610b01d3dfaa0f8e2289574761cc0312e187e3b1/exercises/dot-dsl/tests/dot-dsl.rs#L50).

According to Graphviz, there should be two nodes for a [graph with one edge](https://dreampuf.github.io/GraphvizOnline/#graph{a--b}).

So, the following assertion doesn't hold:
https://github.com/exercism/rust/blob/610b01d3dfaa0f8e2289574761cc0312e187e3b1/exercises/dot-dsl/tests/dot-dsl.rs#L55

**Comment by iurii-kyrylenko** [comment]
Perhaps the issue isn't so important, considering this is an example intended only for educational purposes.

**Comment by coriolinus** [comment]
Thank you for pointing this out, but as you say, this is a simplified example for educational purposes; it is not intended to track the DOT format precisely.
