### ISSUE TITLE
How to contribute mentoring notes?

### ISSUE THREAD

**Issue by happysalada** [exercism/rust#958]
I couldn't find where to contribute mentoring notes on an exercise. I find those very helpful and there are a couple missing. I'm sure it would help reviews. 
Let me know if this is not the right place to ask this question, and I'll move it appropriately.

**Comment by petertseng** [comment]
mentoring notes are at https://github.com/exercism/website-copy/tree/master/tracks/rust/exercises

**Comment by happysalada** [comment]
Thanks!
