### ISSUE TITLE
[Suggestion] For an exercise, add hints from The Rust Book or other sources needed to complete the task.

### ISSUE THREAD

**Issue by frenchiveruti** [exercism/rust#959]
I'm fairly new at Rust (and programming in general), and I like to be challenging myself to different exercises whenever is possible so I can get a better understanding of what is used for what and also for keeping it interesting.  
What I would like to see is that in the "Instructions" of each task or challenge, a little "help" or "orientation" on how to solve the problem, this, specially as a beginner it's crucial because sometimes we don't even know what we can "build" with the tools we already know.  
As an example, I'll use this exercise: https://github.com/exercism/rust/blob/master/exercises/nth-prime/README.md

It may look "easy", but with Rust, you run quite fast to the issue that Arrays are fixed in length and also you can't really mess with them that much, and all the solutions to this problem that exist around the internet (The ones written in C++ Java or C#) make use of arrays that can be expanded or shrunk in size on execution.  

So, keeping up with what I have in mind as a suggestion, a good thing to add (at least here) would be:  

- Point to the user that you will have to use another tool, I still didn't figure out which one, maybe vectors? (Chapter 8.1 of The Book) in order to be able to solve the issue. A way of doing so would be "In order to complete this task you'll need to read the N.n chapter of The Book", or similar.
- Maybe mention how listing primes can be done, I think the Sieve of Eratosthenes is the intended method for this one? I'm still not sure and I couldn't implement it.  

My background in math is not the best I admit it, but the tags for the exercise for example don't mention "Arrays" or "Vectors", just goes by with a generic "Math", "Loops" and "Primes" which really doesn't help, they're really general.  
Also the phrase from the README.md: "If your language provides methods in the standard library to deal with prime numbers, pretend they don't exist and implement them yourself."

Thanks

**Comment by efx** [comment]
@frenchiveruti thank you for the great feedback! 
> It may look "easy", but with Rust, you run quite fast to the issue that Arrays are fixed in length and also you can't really mess with them that much,

Coming from JavaScript I am often tripped up by nuances like these.

I don't think we maintainers have any plans for the v2 track, but Exercism's V3 effort will have hints tailored to each exercise. Here is one `hints.md` [file](https://github.com/exercism/v3/blob/cb0e167b2b69bfb40814fd84e71f02e90e1c06ef/languages/rust/exercises/concept/enums/.docs/hints.md) that shows how we are introducing them. 

So I'm not really addressing your feedback but will keep it in mind as we keep working on the [v3](https://github.com/exercism/v3) track. Also, feel free to join us if you want to help make v3 even better!

**Comment by coriolinus** [comment]
A further complication is that there are usually several potential approaches to solving a problem, and we don't know which a student will chose. For example, the [nth-prime example](https://github.com/exercism/rust/blob/master/exercises/nth-prime/example.rs) doesn't use arrays or vectors at all. 

Vectors are, however, the right tool when you need a variably-sized array.

One of the goals of v3 is to make the core problems smaller and more constrained, so that it's easier to link people to the appropriate documentation ahead of time. Hopefully that will help!

**Comment by frenchiveruti** [comment]
> 
> 
> A further complication is that there are usually several potential approaches to solving a problem, and we don't know which a student will chose. For example, the [nth-prime example](https://github.com/exercism/rust/blob/master/exercises/nth-prime/example.rs) doesn't use arrays or vectors at all.
> 
> Vectors are, however, the right tool when you need a variably-sized array.
> 
> One of the goals of v3 is to make the core problems smaller and more constrained, so that it's easier to link people to the appropriate documentation ahead of time. Hopefully that will help!

I understand that there's different approaches for a given exercise, that's for sure, but maybe keep it as an "spoiler" and make it so that if you want a "hint" to put you on the track of the solution instead of bumping into walls and rediscovering the wheel.

**Comment by coriolinus** [comment]
This tracks well with the `hints.md` file required by the v3 spec.
