### ISSUE TITLE
Simple-linked-list: test_from_slice test wrong?

### ISSUE THREAD

**Issue by RalfNorthman** [exercism/rust#960]
Maybe I'm missing something, but since the list pops from the front shouldn't `Some("1")` be first instead of last (and so on)?

Test as it is written now:
```
#[test]                                                                                
  fn test_from_slice() {                                                                 
      let mut array = vec!["1", "2", "3", "4"];                                          
      let mut list: SimpleLinkedList<_> = array.drain(..).collect();                     
      assert_eq!(list.pop(), Some("4"));                                                 
      assert_eq!(list.pop(), Some("3"));                                                 
      assert_eq!(list.pop(), Some("2"));                                                 
      assert_eq!(list.pop(), Some("1"));                                                 
  } 
```

**Comment by coriolinus** [comment]
The list doesn't pop from the front; it pops from the list head. See discussion in https://github.com/exercism/rust/issues/834 and [here](https://github.com/exercism/rust/pull/863#pullrequestreview-282561411).

**Comment by RalfNorthman** [comment]
Oh, my mistake, I come from a tradition (e.g. R, elm) where _head_ is at the front and _tail_ is at the back.

Doesn't that sound more intuitive than vice versa?

**Comment by coriolinus** [comment]
Yes. Unfortunately, saying that the head is at the front has its own set of
semantic issues.

Ideally we'd say "top" instead of "head", because we want stack semantics,
but that's even more confusing for students who haven't heard of stacks.
