### ISSUE TITLE
Include debug config for VSCode

### ISSUE THREAD

**Issue by indo-dev-0** [exercism/rust#965]
I ran into an error while working through a practice step and I'm struggling to get debugging working.  I'm new to systems languages, but not programming and getting debugging working is time-consuming and confusing.  It would be helpful if the setup instructions included a recommended extensions pack for VSCode (like the LLDB, debugger, Rust Analyzer, etc) and a debug config were included in each lesson.

I understand that VSCode isn't the only IDE available for Rust, but it is [the most popular IDE for Rust](https://blog.rust-lang.org/2020/04/17/Rust-survey-2019.html#ides-and-tooling---a-closer-look) and the Rust Analyzer VSCode extension is maintained within the Rust Analyzer git repo.

**Comment by coriolinus** [comment]
Hi!

Thanks for the suggestion. However, after discussion with some other maintainers, it's just out of scope for the Rust track. We will not add detailed debugging instructions or configuration for any particular IDE, editor, or platform: there are plenty of alternatives that a student can choose, and it would require an overwhelming amount of work to attempt to exhaustively cover every permutation. 

VS Code may be the most popular editor, but it has just over a third of developer use, according to the survey you linked. That's not sufficient to privilege it.
