### ISSUE TITLE
Replace Travis CI with Github Actions

### ISSUE THREAD

**Issue by coriolinus** [exercism/rust#974]
The Rust track has a fairly extensive set of [automatic tests and checks for PRs](https://github.com/exercism/rust/blob/master/.travis.yml), most of which are expressed as scripts in the [`_test`](https://github.com/exercism/rust/tree/master/_test) folder. This all works fine, and has for years now. However, they can be improved.

The biggest expected improvement is in readability: instead of a single red X on a failing commit, requiring someone to dig through the Travis logs to figure out what went wrong, it's relatively simple in Github Actions to break each test into its own independent check, and get a comprehensive list of successes and failures for each commit. 

A related expected improvement is in parallelism: rust compilation can sometimes be slow, and the test suites are sometimes large. If we can perform more checks in parallel, slowdowns should matter less. 

Criteria for acceptance:

- Create appropriate configuration to express all existing tests as independent checks in Github Actions.
- Remove Travis configuration entirely.

**Comment by dgunay** [comment]
I think I'll take a shot at this.

**Comment by coriolinus** [comment]
Closed by #975.
